### ISSUE TITLE
Autofill not working on some forms/sites

### ISSUE THREAD

**Issue by OlafLostViking** [QupZilla/qupzilla#1604] opened 2015-02-06 15:31 UTC
Using QupZilla 1.8.6 to login to copy.com won't fill out their login form even though QupZilla is perfectly able to save the data for multiple accounts (correctly stored in the password manager). Other "dynamic"/modal login forms like on gog.com work, though.

This is not a current regression as I already experienced this behaviour in an earlier version and is most likely triggered by changes on the side of copy.com's website design.

**Comment by nowrep** [comment] 2015-02-08 11:06
This is duplicate of #999

**Closed by nowrep** 2015-02-08 11:06 UTC
Labels: Duplicate

**Comment by OlafLostViking** [comment] 2015-02-08 22:06
Oh, I'm sorry, David. You're right, of course. :-(
