### ISSUE TITLE
Little annoyances...

### ISSUE THREAD

**Issue by quphub** [QupZilla/qupzilla#1784] opened 2015-11-26 08:36 UTC
QUPZILLA 1.8.9
WINDOWS XP2 PRO

1) Download Manager always says "REMAINING FEW SECONDS"

2) Tools>Preferences>Other>SpellCheck settings
Hidden window.

3) Can't open automatically Bookmark in new tab.

**Comment by JHooverman** [comment] 2015-11-26 09:16
Regarding 1): Please see #1606
Regarding 2): Please see #1777

**Comment by quphub** [comment] 2015-11-26 09:28
Thanks for the kind and speedy answer !

QupZilla smells as a great browser !   :)

**Comment by cranes-bill** [comment] 2015-11-26 12:31
Regarding 3): There is no settings option to open bookmarks in new tab, so that's not a bug, but you can use middle click instead.

**Comment by quphub** [comment] 2015-11-26 13:13
Thanks for your answer !
General behavior of middle click on my pc is 'close app'...
"Open history and bookmarks in new tab" in Preferences>Tabs could be useful.

**Comment by nowrep** [comment] 2015-11-26 13:14
Then use Ctrl+Left Click

**Comment by quphub** [comment] 2015-11-26 13:19
Bingo ! nowrep, that does the trck !
Thanks, bro.!

**Comment by JHooverman** [comment] 2015-11-26 14:09
Closing this issue as solved (3) and as duplicate (1) + (2).

**Closed by JHooverman** 2015-11-26 14:09 UTC
Labels: Duplicate, Other
