### ISSUE TITLE
Faulty scrolling after middle clicking a link

### ISSUE THREAD

**Issue by tsujan** [QupZilla/qupzilla#2242] opened 2017-03-07 20:41 UTC
When a link is middle clicked and opened in a new tab, the tab page tries to scroll to the target too soon, namely, *before* the page is completely loaded. So, the link target goes outside the visible part of the page after the page is fully loaded.

This is easily reproducible with the offline Qt doc.

**Comment by nowrep** [comment] 2017-03-15 10:01
This is bug in QtWebEngine, you can observe the same behavior in recent QtCreator version (that use QtWebEngine for doc viewer).

**Comment by tsujan** [comment] 2017-03-15 10:14
I haven't read the code, so I may be totally lost, but isn't it possible to use a slot with `QTimer::singleShot()` for that?

**Comment by nowrep** [comment] 2017-03-15 11:21
Sure, but this should be fixed in QtWebEngine instead of workarounding it.

**Comment by tsujan** [comment] 2017-03-15 11:32
My 2 cents: The idea is ensuring that a process is really finished and keeping the sequence. `QTimer::singleShot()` and `QCoreApplication::processEvents()` are needed by many apps in some places.

**Comment by nowrep** [comment] 2017-03-15 11:38
Yes, but it won't help because it is not even the issue and also because Chromium runs in separate process, so deferring action to next event loop cycle solves nothing.

The problem is that the view doesn't have correct size when page finishes loading in background tab (it gets resized on the first show).

**Comment by tsujan** [comment] 2017-03-15 11:47
> ... Chromium runs in separate process

OK. So I *was* lost ;)

**Closed** 2017-03-15 12:29 UTC
Labels: QtWebEngine
