### ISSUE TITLE
Not possible to save any picture

### ISSUE THREAD

**Issue by Piteur57** [QupZilla/qupzilla#1774] opened 2015-11-17 17:49 UTC
Hello !
On Xubuntu 14.04, I just installed the new 1.8.9 version of QupZilla: it is still not possible to save a picture.
When I try, it looks like I want to save TWO files. And everything is blocked.
This problem occurred with version 1.8.8, I believe.
![screen-2015-11-17_18-18-07](https://cloud.githubusercontent.com/assets/15894628/11219653/e668ed20-8d5b-11e5-9096-61e5a8286472.jpg)
Thanks for all, anyway.

**Comment by ke7ofi** [comment] 2015-11-17 17:52
This may be a duplicate of #1606.

**Comment by nowrep** [comment] 2015-11-17 17:54
It is.

**Closed by nowrep** 2015-11-17 17:54 UTC

**Comment by Piteur57** [comment] 2015-11-17 18:00
Sorry: I didn't see #1606. It's that, but no problem with versions which are earlier than 1.8.8.

**Comment by nowrep** [comment] 2015-11-17 18:02
Because this is Qt 5 specific.

**Comment by Piteur57** [comment] 2015-11-17 18:39
Okay, thanks.
And so? Wait for QT5 corrections?

**Comment by ke7ofi** [comment] 2015-11-17 20:15
@Piteur57 That seems to be the case with a lot of problems, unfortunately.
