### ISSUE TITLE
1.8.6 - CPU Usage High Percentages At Idle...

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1596] opened 2015-01-29 06:54 UTC
Hi,

In 1.8.6 I noticed when it's just sitting idle on the Start Page and I'm not doing anything with QupZilla the CPU percerntages spikes really high at times.

On average it sits idle at ```0.9% - 1.4%``` this in itself is high because tested against Firefox, it sits idle at 0%, nothing... So why this high idle usage in QupZilla?

Also with QupZilla sitting on the Start Page, I saw in htop it spike up to 40% and then another time for 80% sitting at these high percentages for a few seconds. Why is QupZilla, sitting idle on the Start Page and doing nothing going to surge the CPU this high?

**Comment by moulei** [comment] 2015-01-29 06:54
Forgot to mention this is in Slackware...

QT 5.4.0
Application version 1.8.6
WebKit version 538.1

**Comment by The-Compiler** [comment] 2015-01-29 07:03
This could be the same issue as https://github.com/The-Compiler/qutebrowser/issues/272 maybe? If so, then it should be fixed in Qt 5.4.1: https://codereview.qt-project.org/#/c/100753/

**Comment by JHooverman** [comment] 2015-01-29 08:31
I am not able to reproduce this issue with

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jan 25 2015 16:47:02
Platform: openSuSE Tumbleweed (Linux)

As @The-Compiler stated, this is hopefully fixed in versions > Qt-5.4.0.

**Comment by moulei** [comment] 2015-01-30 05:59
Ok, guess going to have to wait for 5.4.1 for another bug to get squashed... :(

thanks

**Closed** 2015-06-02 14:02 UTC
Labels: QtWebKit, Reported upstream, Resolved upstream
