### ISSUE TITLE
Mouse scroll wheel and multi monitor issue

### ISSUE THREAD

**Issue by KaMiila** [QupZilla/qupzilla#1641] opened 2015-04-17 20:43 UTC
If you are on dual monitors with NVIDIA without Xinerama, scrolling in qupzilla using the mouse wheel is very buggy.

To replicate this behavior open qupzilla on one monitor, then with your mouse start doing something (anything, even a single mouse click on the second monitor), then go back to qupzilla and try to scroll with the mouse wheel.  It will automatically scroll you back to almost the top of the website you are visiting, which is a huge pain when trying to read the news or any long website.

I suspect this is related to QT5 and/or qtwebengine but have no way to verify this.

**Comment by OlafLostViking** [comment] 2015-05-15 17:04
I thought I have unique problems with my system... ;-). I am also using an nvidia based laptop with an additional external monitor attached (my main/this machine is still on KDE workspaces 4 using KF5 applications where available) and am encountering the same problem a few times a day. However, I can *not* reproduce it the way you describe but am encountering the problem *without* leaving the desktop, too.

I haven't found a way to reproduce, so I cannot give any further hints. Sorry. But good to know that there are others affected :-p

**Comment by nowrep** [comment] 2015-05-22 22:24
I can confirm this issue with Qt 5.4 QtWebEngine. Seems to be fixed in Qt 5.5.
@OlafLostViking I have never experienced it with QtWebKit.

**Comment by OlafLostViking** [comment] 2015-05-24 11:08
This is from the About dialog in QupZilla:

Application version 1.8.6
WebKit version 538.1
© 2010-2014 David Rosca
Build time: Jan 27 2015 00:57:55 
http://www.qupzilla.com
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.6 Safari/538.1

(And it just happened while entering this text ;-) )

**Comment by KaMiila** [comment] 2015-07-16 23:33
just compiled t 5.5.0, qtwebengine 5.5.0, and todays git pull of qupzilla, still getting this issue.....

**Comment by nowrep** [comment] 2015-10-22 15:36
This looks similar to https://bugreports.qt.io/browse/QTBUG-47753

**Closed by nowrep** 2015-10-22 15:36 UTC
Labels: QtWebEngine, Reported upstream

**Comment by OlafLostViking** [comment] 2016-05-02 17:36
The problem is still valid for:

Application version 2.0.0 (c0026af63e)
QtWebEngine version 5.6.0
© 2010-2016 David Rosca
https://www.qupzilla.com
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.0.0 Chrome/45.0.2454.101 Safari/537.36

**Comment by Martii** [comment] 2016-05-02 18:50
Since I just happen to have the same mfg on GPU and dual monitors if either of you can give more exact steps to duplicate I'd be happy to try them.

**Comment by meyerm** [comment] 2016-11-10 20:10
So, just to be sure: Neither @Martii nor @nowrep ever encountered this effect where the "website view" just scrolls up when you want to use the mouse wheel to scroll down?

It is not reproducible, since it's non-deterministic. Is there some kind of log that we can extract after it happened?

**Comment by OlafLostViking** [comment] 2016-11-10 20:13
So neither @Martii nor @nowrep ever encountered this effect on current QupZilla? I am now using 2.0.2 on WebEngine 5.7.0 and scrolling through long youtube video lists f.ex. lets the "webview" jump upwards quite often. It is not deterministic :-/

Is there some kind of log we could extract if this happens again that could help you?

**Comment by Martii** [comment] 2016-11-11 17:56
@OlafLostViking 
My distro with X11 hides if Xinerama is actually running because Xorg made some different defaults in my newer distro but before it did this it was running twinview from nVidia. Have any of you tried the free video driver vs the proprietary? I've never had another window "jump upwards" even on a recent retest with YouTube. Again if there are some specific steps to reproduce it would helpful. It seems to me if an event is being sent from a scroll event `xev` might be a starting point to observe... it's very "cryptic" and low level as it shows coordinates and mouse button presses and it can rule in/out mouse actions... so they'll need to be translated and that is very lengthy... but without exact STRs it's not going to be fruitful on debugging. As nowrep mentioned there could be a Qt issue as well with your platform.

**Comment by OlafLostViking** [comment] 2016-12-23 02:16
I have a page here where it seems to happen most of the time:

http://forum.golem.de/read.php?105994,4691640

Just scroll into about the middle of the comments, let the browser rest for a minute or so (because you want to read a long comment carefully :) ) and then use the scrollwheel to go down. It doesn't happen all of the time, but most of it.
