### ISSUE TITLE
When returning from link in long document, returns to top, not link position.

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1813] opened 2015-12-16 22:29 UTC
Don't know if this should be a bug or a feature request, but it's definitely a usability problem.  You can reproduce the problem here (for one example, though it seems to happen everywhere: http://doc.qt.io/qt-4.8/stylesheet-reference.html#list-of-stylable-widgets  Scroll down several pages, follow any interesting link, say QScrollBar, then use Alt-Left to return.  You're positioned at the top of the document, not the position you were at when you clicked the link.

Again, I'm using version 1.8.9 on OpenSuSE 13.1.

**Comment by Kpvt** [comment] 2016-01-06 11:10
Keep! This is an old problem. The browser and therefore do not want to use it!

**Comment by JHooverman** [comment] 2016-01-06 11:54
@Kpvt: I removed your second comment, because we might loose this issue when we put it here. In case there already exists a bug report for this, then please add your comment there. If not, you are kindly asked to open a new issue with a reproducible error description.

**Comment by nowrep** [comment] 2016-12-26 19:29
This should be fixed in QupZilla 2.

**Closed by nowrep** 2016-12-26 19:29 UTC
Labels: Bug
