### ISSUE TITLE
New Windows theme messed in 2.2.5

### ISSUE THREAD

**Issue by smarquespt** [QupZilla/qupzilla#2580] opened 2018-01-30 09:49 UTC
The release 2.2.4 introduced a great new Windows theme. But 2.2.5 has made some regressions because now we have a great interface and bad dialogs. The interface is the same but dialogs made me look like using an older system. Also the menu bar, when hidden, is shrinked on it´s width.

@nowrep Have you made some changes that affect themes?
![1](https://user-images.githubusercontent.com/1302668/35559524-d91000e8-05a2-11e8-86f4-521ec336dfea.jpg)
![2](https://user-images.githubusercontent.com/1302668/35559525-d9432f2c-05a2-11e8-9fc4-b3337e3d7060.png)

**Comment by nowrep** [comment] 2018-01-30 09:51
Nothing was changed in themes that could result in this. It looks like issue with Qt 5.10 as 2.2.4 was still using Qt 5.9.

**Comment by cranes-bill** [comment] 2018-01-30 16:33
Most likely **5.9** was buggy, because that seems be the „Windows“ style (which is from Windows 95 era :-D). So if the default style for Windows is „Windows“, it should look just like that. My guess is that on the previous version the „Windows style“ was not applied and Qt was used the fallback style (which probably is Fusion).

**Comment by srazi** [comment] 2018-02-01 12:07
Here on Win10 it seems OK.

![qupzilla](https://user-images.githubusercontent.com/1328454/35677619-96de8414-0765-11e8-8fd5-30ad6fa6ceac.PNG)
![qupzilla-win](https://user-images.githubusercontent.com/1328454/35677622-97e6df8c-0765-11e8-9245-90861faeacbb.png)

**Comment by smarquespt** [comment] 2018-02-01 23:04
If it matters I'm also using windows 10 but qupzilla is portable.

**Comment by srazi** [comment] 2018-02-02 11:34
I can reproduce it by installers from site. The screenshots were from compiled version on my own computer. 

@nowrep I copy qupzilla.exe and qupzilla.dll from installers to my compiled version and then again the issue is present. So do you think some libraries were missed from AppVeyor?

**Comment by nowrep** [comment] 2018-02-02 11:38
@srazi No idea, might be AppVeyor Qt built without QWindowsVista (or whatever is the "current" windows theme in Qt called) theme? Or windows platform plugin not loading, but in that case the app would not start at all...

**Comment by srazi** [comment] 2018-02-02 20:45
Fixed by 03bc614baca1f158e8af0a6b286fa7c62a55b57b

@nowrep Fixed releases based on tag v2.2.5 are available [here](https://github.com/srazi/qupzilla/releases/tag/v2.2.5-1)

**Closed by srazi** 2018-02-02 20:45 UTC
