### ISSUE TITLE
Feature request: Option "don't ask when close more then one tab" when try to close from right-click on tab   

### ISSUE THREAD

**Issue by iondissonance** [QupZilla/qupzilla#2178] opened 2017-01-24 03:54 UTC
http://i.imgur.com/U7LNHij.png

This option don't work :(

Last 24b6db8 build.

**Comment by Martii** [comment] 2017-01-24 05:52
Works in OS X with 24b6db866a7239655d796ae0c53a3ce58ac1a61d 

What is your platform info?

**Comment by iondissonance** [comment] 2017-01-24 05:54
openSUSE Tumbleweed, x86_64, Qt 5.7.1

**Comment by Martii** [comment] 2017-01-24 06:04
I currently have Leap in a VM... so will try to see if the current VM *(updated twice since my last check)* will run Tumbleweed. Till then I'll update the Leap and test there... will take some time.

**Comment by iondissonance** [comment] 2017-01-24 06:07
https://build.opensuse.org/package/show/home:mephisto/qupzilla

my git repo

**Comment by Martii** [comment] 2017-01-24 08:51
Hmm Qt 5.8 went out of rc status... will try with 5.7.x though.

**Comment by iondissonance** [comment] 2017-01-24 11:54
>did you mean that it always asks regardless of the setting preference?

Yes!

**Comment by Martii** [comment] 2017-01-24 12:00
Okay then... confirmed.

Some code point refs:
* https://github.com/QupZilla/qupzilla/blob/24b6db866a7239655d796ae0c53a3ce58ac1a61d/src/lib/preferences/preferences.cpp#L237
* https://github.com/QupZilla/qupzilla/search?utf8=%E2%9C%93&q=AskOnClosing

**Comment by nowrep** [comment] 2017-01-24 12:01
It should only ask when you don't have restore session option.

**Comment by nowrep** [comment] 2017-01-26 17:06
I can't reproduce it, it works as expected. If you have restore session enabled, it won't ask you. If you don't, it will ask you if you close more than one tab.

**Comment by iondissonance** [comment] 2017-01-26 23:04
>If you don't, it will ask you if you try to close window with more than one tab.

Even with disabled checkbox "Ask when closing multiple tabs"? Is it logical?

**Comment by Martii** [comment] 2017-01-26 23:19
@nowrep 
Firstly I usually open to a blank tab... tried on the General tab, after launch then restore session, which is where you are saying this option affects... so the terminology is again a bit unusual here for your statement. e.g. "Restore the tabs on launch yet only ask when closing multiple tabs"... this isn't happening either in OS X.

Secondly the terminology is "Tabs"... what to do when a "tab action" of "closing multiple tabs" is how I interpret it. Perhaps some verbage change of the strings would be in order and probably some identifiers.

Thirdly... try opening a few tabs and then pick one in the middle. Then right click it and close tabs to the right... prompts.

**Comment by iondissonance** [comment] 2017-01-30 10:42
Video https://youtu.be/hIu7c6pT1_c

**Comment by cranes-bill** [comment] 2017-01-30 13:36
This option is when you want to quit QupZilla but there is more then one opened tabs, but is not when  you want to leave one tab opened. So i thing this is not a bug.

**Comment by iondissonance** [comment] 2017-01-30 13:39
Oh. In this case, this "bug" is feature request.

**Comment by Martii** [comment] 2017-01-30 20:40
@cranes-bill 

> This option is when you want to quit QupZilla but there is more then one opened tabs...

Then this would also be a bug in OS X... set to "General&rarr;Restore session" *(and with blank tab)* and "Tabs&rarr;Ask when closing multiple tabs". Does **not** prompt when multiple tabs are open and <kbd>&#8984; + Q</kbd>.

**Comment by cranes-bill** [comment] 2017-01-30 21:03
Should not [ask](https://github.com/QupZilla/qupzilla/issues/2178#issuecomment-274785245) when **_Restore session_** is enabled.

**Comment by nowrep** [comment] 2017-01-30 21:05
> Should not ask when Restore session is enabled.

That's correct. The only issue I see is that it is not mentioned in the preferences and thus it may confuse the user what really is that option doing.

**Comment by Martii** [comment] 2017-01-30 21:07
I'm really not looking forward to getting a YT account just to explain this... even with "Open blank page" it never prompts in OS X. I'll table it now since I'm working on the build structure documentation at the moment.

**Comment by cranes-bill** [comment] 2017-01-30 21:10
**Just a note:** Firefox has the same behavior for _**Close the other tabs**_ option

**Comment by stefonarch** [comment] 2017-02-06 09:03
Writing here because somehow related: I've not checked "ask before closing more tabs" in preferences > tabs, but when I click "close right|left tabs" from tab bar it asks and takes me to clicks more to close them.

So IMHO that is not a consistent behavior.

(but  thanks anyway for the options, I missed them!)

**Comment by cranes-bill** [comment] 2017-02-06 09:28
The presumption here is that when you selecting some context menu option, you now what you are doing, but when you closing main window, you might have not been noticing that you have some opened tabs.
Sorry for the bad English!

**Comment by stefonarch** [comment] 2017-02-06 11:27
Indeed: when I'm closing right or left tabs I know what I'm doing and clicking   the OK button is unnecessary therefor.

**Comment by Martii** [comment] 2017-02-07 12:15
> The presumption here is that when you selecting some context menu option, you now what you are doing...

You should try that on a touch pad that is super sensitive to accidental clicks.

**Comment by iondissonance** [comment] 2017-02-08 07:14
Option will suit all.

**Comment by cranes-bill** [comment] 2017-02-08 20:39
@Martii, you are joking. Even i can accept any other argument exclude this one. Touch pad sensibility depends just of the settings.

**Comment by Martii** [comment] 2017-02-08 20:57
@cranes-bill 
Actually I'm quite serious... settings have nothing to do with it. Placement of touch pads affects everything which is why I usually disable them on notebook/laptops. However some wifi keyboards don't give the option nor do they always have settings to disable tap clicks. I've been in the business for many decades and experienced and heard of many "issues" with touch pads on thousands of machines which is why there's usually an optional prompt for critical closures including tabs. I've also experienced defective mouse drivers due to either hardward issues or some other software incompatibility... that could also affect things.

So your assumption is incorrect from my mastered experience.

**Comment by iondissonance** [comment] 2017-04-02 17:21
Want option :(

**Comment by srazi** [comment] 2017-04-02 18:13
> Want option :(

To be honest, I don't get what you want. But from the video it seems you want an option to disable asking `Do you really want to close other tabs?` on closing all other tabs?

**Comment by iondissonance** [comment] 2017-04-02 22:44
Option (checkbox) to disable alert when try to close more then one tab from right-click context menu on tabs.

**Comment by srazi** [comment] 2017-04-03 07:11
@nowrep How about using `CheckBoxDialog` instead of `QMessageBox::question` in closeAllButCurrent(), closeToRight() and closeToLeft()?

**Comment by nowrep** [comment] 2017-04-03 07:12
@srazi Sounds good.

**Closed** 2017-04-05 08:27 UTC
Labels: Bug

**Comment by iondissonance** [comment] 2017-04-05 08:35
Brilliant.

**Comment by Martii** [comment] 2017-04-05 08:36
Silly question... where in the preferences is this now?

**Comment by srazi** [comment] 2017-04-05 08:46
> Silly question... where in the preferences is this now?
It is a checkbox in message box that warns about closing tabs.

**Comment by Martii** [comment] 2017-04-05 08:47
Interesting feature... 3 sets of "don't ask this again"... wonder how to reset it through the preferences or will I get to create a new profile if I am a user who accidentally tries it out. ;) Still a much needed feature as is. Thanks.

**Comment by srazi** [comment] 2017-04-05 10:39
As I know there is no GUI option to reset them. You can find them in `settings.ini` as sub-key of `[Browser-Tabs-Settings]`:
```ini
[Browser-Tabs-Settings]
AskOnClosingAllButCurrent=false
AskOnClosingToLeft=false
AskOnClosingToRight=false
...
```

**Comment by Martii** [comment] 2017-04-05 17:08
Awesome. Thanks again.
