### ISSUE TITLE
download manager in tab instead of a separate window [future request]

### ISSUE THREAD

**Issue by soocki** [QupZilla/qupzilla#1892] opened 2016-03-23 19:52 UTC
As per title is it possible to include an option have the download manager opened as a tab not in the new window?

**Comment by JHooverman** [comment] 2016-03-23 21:03
Closing this issue as a duplicate of #1348.

**Closed by JHooverman** 2016-03-23 21:03 UTC
Labels: Duplicate

**Comment by soocki** [comment] 2016-03-23 21:04
Sry you're right.
