### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by fturco** [QupZilla/qupzilla#2046] opened 2016-07-30 18:36 UTC
I have qupzilla-2.0.1-2 on a Parabola GNU/Linux-libre system. It crashes on startup, even after deleting configuration files and caches (`~/.config/qupzilla`, `~/.cache/qupzilla` and `~/.QupZilla`). I obtained a gdb backtrace after having recompiled several packages with debug symbols:

- qupzilla-2.0.1-2
- libxcb-1.12-1
- libpulse-9.0-1
- mesa-12.0.1-5
- qt5-base-5.7.0-1

I couldn't recompile qt5-webengine and libevent. The former needs more than 7 GB of RAM and makes my computer crash.

[qupzilla.txt](https://github.com/QupZilla/qupzilla/files/392044/qupzilla.txt)

Please tell me if you need other informations.

**Comment by nowrep** [comment] 2016-07-30 18:43
Duplicate of #2033 and #1842

**Closed by nowrep** 2016-07-30 18:43 UTC

**Comment by nowrep** [comment] 2016-07-30 18:45
You can try running QupZilla with `qupzilla --disable-gpu`

**Comment by fturco** [comment] 2016-07-30 18:58
Sorry for having reported a duplicate bug. And thank you for the suggestion: Qupzilla doesn't crash if I use the `--disable-gpu` option. I'll check if I have to report a bug with the nouveau package.

**Comment by fturco** [comment] 2016-07-30 19:09
It seems a bug has already been filed for nouveau: https://bugs.freedesktop.org/show_bug.cgi?id=91632
