### ISSUE TITLE
"Work offline" feature automatically triggered/falsely shown

### ISSUE THREAD

**Issue by OlafLostViking** [QupZilla/qupzilla#1750] opened 2015-11-07 10:23 UTC
When losing network connection, qupzilla seems to switch an internal offline state and won't reconnect to websites again (telling my I've disabled the network). I have to choose "Work Offline" from the File menu and _activate_ it (so that the marker becomes visible) to be able to go online again.

**Comment by nowrep** [comment] 2015-11-07 10:55
Duplicate of #1744

**Closed by nowrep** 2015-11-07 10:55 UTC
Labels: Duplicate
