### ISSUE TITLE
Youtube Full screen not working

### ISSUE THREAD

**Issue by HelmiRepo** [QupZilla/qupzilla#1849] opened 2016-02-07 19:57 UTC
Hello, i'm facing some issue with youtube full screen 
I'm running :
- xubuntu 15.04 64 bits with intel video card
- Qt 5.4.1
- Webkit 538.1
- Qupzilla 1.8.9

**Comment by JHooverman** [comment] 2016-02-07 20:49
Duplicate of #1127

**Closed** 2016-02-07 20:49 UTC
Labels: Duplicate

**Comment by HelmiRepo** [comment] 2016-02-07 21:37
i undrestand thanks anyway

2016-02-07 21:50 GMT+01:00 Jonathan Hooverman <notifications@github.com>:
