### ISSUE TITLE
Why is QupZilla not using the default Plasma scrollbar?

### ISSUE THREAD

**Issue by francoism90** [QupZilla/qupzilla#1897] opened 2016-03-28 12:45 UTC
Just a bit of a low priority question: Why does the scrollbar differ when using QupZilla on Plasma?
Is it possible to use the default style or is it a configuration error at my end?

Thanks for creating this wonderful browser. :)

**Comment by nowrep** [comment] 2016-03-28 20:40
I assume you are using QtWebEngine. The problem is that Chromium uses its own scrollbars. There is a way to change the scrollbar look, but it must be done in QtWebEngine (and I think there is no plan for it).

**Comment by ke7ofi** [comment] 2016-03-29 01:06
How feasible would it be to complain about this upstream?

**Comment by jamesqf** [comment] 2016-03-30 19:25
There is a way to change the appearance of the scrollbar, at least in Linux.  It's fairly simple to do, but frustrating to figure out because documentation is difficult or impossible to find.  I made some notes here: https://github.com/QupZilla/qupzilla/issues/1816

Which raises a question I've had for some time: shouldn't there be some sort of discussion forum for qupzilla, so we can share info on things that aren't really bugs, just lack of easily-findable information how to do things?

**Comment by Martii** [comment] 2016-03-30 19:33
> shouldn't there be some sort of discussion forum for qupzilla

IRC mentioned at https://github.com/QupZilla/qupzilla#qupzilla-web-browser and also comments on the blog.

**Comment by francoism90** [comment] 2016-04-01 09:00
Thanks for the info. :)
It would be great to have it native, instead of an own style (just to have the same look in all apps on KDE).

Should I report it upstream?

@nowrep This is for qt4? Qt5 doesn't have an qt-config anymore. Isn't QupZilla written in Qt5? Sorry, noob here.

**Comment by AcarBurak** [comment] 2016-04-01 09:30
@francoism90 There's an excellent qt5 config utility, much beter than qt4-config: qt5ct.

**Comment by jamesqf** [comment] 2016-04-01 18:58
@ke7ofi: Wikis and such are (IMHO, anyway) far less usable for question & answer type discussions.

**Comment by ke7ofi** [comment] 2016-04-02 00:58
That's true, but procedures for fixing problems are best there. New solutions can be found places like this or on IRC channels.

**Comment by r-a-v-a-s** [comment] 2016-04-05 17:39
Using 2.0.0 I'm seeing the native OS X scrollbar.
Something to note is the change in built-in styles:
http://blog.qt.io/blog/2012/10/30/cleaning-up-styles-in-qt5-and-adding-fusion/

Therefore, "Plastique" (as suggested in jamesqf tip) won't be available.
The "Fusion" style is the new cross-platform style introduced in Qt5.
The styles available on OS X are: Windows, Macintosh and Fusion.
Exposing an option to choose these is fairly trivial (I've done it before);
however, I'm not sure how it would work with the custom themes of QupZilla.
My guess is if you aren't seeing a Plasma scrollbar by default, then it's not offered by Qt.

Regarding the lack of a forum, I agree with jamesqf.
Information is more organized an easier to find on a forum,
as opposed to chatrooms.
There are free options:
http://www.prophpbb.com/
http://www.nabble.com/

Also, it seems like https://gitter.im/ is an upgrade from IRC.
- github flavored markdown (emoji / syntax highlighting)
- repository activity sidebar
- one-click access for github users
- uses github user profiles
- optional email notifications when the browser is closed

**Comment by cranes-bill** [comment] 2016-04-06 04:57
Just a note:
As a workaround, the scrollbar style can be changed with user css.

**Comment by jamesqf** [comment] 2016-04-06 05:12
@cranes-bill: I don't think that's true. At least I spent quite a bit of time trying to do it with user CSS, but failed, as described in the link above.  Had to resort to editing the theme - a process I still don't really understand, so if you do know how to do it with CSS, please share!

**Comment by jamesqf** [comment] 2016-04-06 05:21
@ke7ofi: But there's a difference between reporting a 'problem' - that is, something that might be a bug in the code - and being able to ask how to do something, as for instance this discussion about changing the scrollbar.  Qupzilla's default works as intended, and most people might well be perfectly happy with it, so it's not in any real sense a bug.  But the default doesn't suit a minority of us, so it'd be nice to have a place to ask questions.

**Comment by r-a-v-a-s** [comment] 2016-04-06 06:12
It looks like you are already on the right path with making a theme.
To understand "qss":
http://doc.qt.io/qt-5/stylesheet.html
http://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qscrollbar

qss is powerful but has its limitations.
For more dramatic changes you need to work with http://doc.qt.io/qt-5/qproxystyle.html#details
but I don't think that is currently possible for QupZilla users.
This isn't surprising considering it's more complicated (requires writing C++).

**Comment by nowrep** [comment] 2016-04-06 06:39
It doesn't use Qt to render the scrollbar, so qss won't help.
You can only modify the scrollbar through user style sheet (CSS).

**Comment by cranes-bill** [comment] 2016-04-06 06:43
> I don't think that's true. At least I spent quite a bit of time trying to do it with user CSS, but failed, as described in the link above. Had to resort to editing the theme - a process I still don't really understand, so if you do know how to do it with CSS, please share!

**Sorry, but i did not posted a link in this issue so far!**

See [here](http://codemug.com/html/custom-scrollbars-using-css/) for example, about the scrollbar pieces and example!
Then you can create your own style, save it on your computer and  set QupZilla to load it and you will see the scrollbar changed.
[Here](http://www.colorzilla.com/gradient-editor/) if you need a help to create gradients.

**Comment by nowrep** [comment] 2016-12-26 19:30
Support for native scrollbars have been added, will be in 2.1 release.

**Closed by nowrep** 2016-12-26 19:30 UTC
Labels: QtWebEngine
