### ISSUE TITLE
Save image as...

### ISSUE THREAD

**Issue by datalife66** [QupZilla/qupzilla#1940] opened 2016-04-13 12:58 UTC
Save image as... is missing from the right click menu. QupZilla 2.0

It is very strange that if I right click on an image before the page is fully loaded Save image as... is there and I can save the image, but if I wait for the page to completely load then Save image as... is gone.

**Comment by Martii** [comment] 2016-04-13 19:18
Platform? In Linux it is currently there in GH build.

**Comment by datalife66** [comment] 2016-04-13 19:53
Windows 10 pro.

**Comment by datalife66** [comment] 2016-04-17 08:21
This issue is on every image on every page that I have loaded. Here is an example URL.
http://whitegadget.com/attachments/pc-wallpapers/85254d1320380902-house-house-wallpaper.jpg

How you been able to confirm the issue?

**Comment by nowrep** [comment] 2016-04-17 08:24
Works fine on Linux, I'll need to test with Windows.

**Comment by Martii** [comment] 2016-04-17 09:54
Reproducible on `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.0.0 Chrome/45.0.2454.101 Safari/537.36` e.g. no image menu items at all:

1. Show Image
2. Copy Image Address
3. Save Image As...
4. Send Image...

**Comment by nowrep** [comment] 2016-04-17 11:17
Can't reproduce on Windows 7, do you actually click on the image?
But even though I get the actions in menu, "Save (image/link) as... " doesn't work for me on Windows.

**Comment by r-a-v-a-s** [comment] 2016-04-17 12:59
I can reproduce it on Windows 7; or rather it is the same issue as:
https://github.com/QupZilla/qupzilla/issues/1937

**Comment by r-a-v-a-s** [comment] 2016-04-17 13:06
In other words, the proper context menu will appear after randomly right-clicking on the image several times. I guess that means you fixed it.

**Comment by Martii** [comment] 2016-04-17 20:46
> Can't reproduce on Windows 7, do you actually click on the image?

Right click yes. 

Sidenote question... I don't have Visual anything from M$ and it's unlikely that I'll add it to my Win7 *(too much drama with Windows right now)*... this is where a nightly would come in handy... at least for Windows. :)

> the proper context menu will appear after randomly right-clicking on the image several times.

Tried that on the Windows release of 2.0 and it still never showed for me. Good idea though... I'll add that to my testing repertoire.

**Comment by r-a-v-a-s** [comment] 2016-04-17 21:36
It works perfectly with the latest commit on OS X.

**Comment by datalife66** [comment] 2016-05-10 16:13
Is this issue being worked on?

**Comment by ubone** [comment] 2017-01-03 10:50
If javascript is not allowed save image as... is missing from menu.
If javascript is allowed it is present.
version 2.0.2

**Comment by cranes-bill** [comment] 2017-01-03 14:54
Just in addition:
This option still does not works as intended to me. It just downloading the images directly, but not ask me for a place and name.

**Comment by nowrep** [comment] 2017-01-03 14:59
Will be fixed in upcoming 2.1 release.

@cranes-bill It initiates normal download request, so it follows your downloads settings.

**Closed by nowrep** 2017-01-03 14:59 UTC
Labels: 2.0, Windows

**Comment by cranes-bill** [comment] 2017-01-03 15:14
So perhaps it just should be renamed to _**Download the image**_, or so...

**Comment by ubone** [comment] 2017-01-03 17:20
@cranes-bill nowrep already answered but maybe you need a little help
Preferences > Downloads > Ask everytime for download location

**Comment by cranes-bill** [comment] 2017-01-03 21:33
In the „**old**“ QupZilla and more of other browsers, that setting does not have effect over „_Save image as..._„ option, so i thought that is a bug.
Nevermind...
