### ISSUE TITLE
Downloading of a specific web-site fails

### ISSUE THREAD

**Issue by ballsystemlord** [QupZilla/qupzilla#1598] opened 2015-01-29 18:19 UTC
I'm using qupzilla for the first time and I can't seem to follow many links. I'm not behind any proxy or other blocking item and I've follow links on the websites successfully before.
Here are two examples:
https://codeload.github.com/QupZilla/qupzilla/zip/master
http://av.vimeo.com/63745/092/13293001.mp4?download=1&token2=1422555243_adeb7640e5a690468e3051f3d9678794&filename=Blinkenlights%20Berlin%20Documentation%20Video-Mobile.mp4
It's ironic  that qupzilla can't download qupzilla.......
I've no idea how to proceed to trouble shoot so please bear with me.
I'me running gentoo linux my qupzilla version is: 1.8.4

Thanks

**Comment by JHooverman** [comment] 2015-01-29 18:43
Please let us know about your configuration (`Menu -> Configuration information`) as shown in the following example:

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jan 25 2015 16:47:02
Platform: openSUSE Tumbleweed (Linux)

**Comment by JHooverman** [comment] 2015-01-30 09:42
I have tested both links you have mentioned with the following configurations:

QupZilla-Version: 1.8.6
Qt-Version: 4.8.6
WebKit-Version: 537.21
Kompiliert am: Jan 30 2015 09:33:55
Plattform: openSUSE Tumbleweed (Linux)
Browser-Identifizierung
Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.21 (KHTML, like Gecko) QupZilla/1.8.6 Safari/537.21

Application version: 1.8.6
Qt version: 5.4.0
WebKit version: 538.1
Platform: openSUSE Tumbleweed (Linux)
Browser Identification
Mozilla/5.0 (X11; Linux i686) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.6 Safari/538.1

The result is the same for both configurations:

(1) codeload.github.com: works in both cases
(2) av.vimeo.com: does not work in both cases as well for firefox. Error message:

`An error occurred while processing your request.`
`Reference #50.6ec09650.1422609323.21d1ca3a`

I recommend, that you upgrade QupZilla to 1.8.6, because the handling of SSLv3 has been modified from 1.8.4 to 1.8.6.

**Comment by JHooverman** [comment] 2015-01-30 12:06
I am closing this issue. If it persists after upgrading QupZilla to 1.8.6, then please re-open.

**Comment by ballsystemlord** [comment] 2015-02-14 21:21
I upgraded to qupzilla 1.8.6 and the problem persists.
I've noticed that qupzilla saves txt and html fine but not files like zip or bz2.
Here are some more urls:
http://www.zaimoni.com/zaiband/Angband.ref/Quickband/Quickband_2_0_2.zip
ftp://ftp.sunet.se/pub/games/Angband/Variant/ZAngband/ZAngband-228-src.zip
I could send more but I keep accidentally killing qupzilla :( instead of hitting close in my window manager.

**Comment by JHooverman** [comment] 2015-02-14 22:01
Just to clarify: After upgrading QupZilla to 1.8.6 you are still not able to download QupZilla from codeload.github.com?
What is your Qt and QtWebkit version?

**Comment by JHooverman** [comment] 2015-02-15 18:38
Regarding your issue with downloading zip-files:

If I click on the zaimoni.com, this window will open:

![zip1](http://i.imgur.com/7L42aHn.png)

I click `Ok` and this window opens:

![zip2](http://i.imgur.com/YBVMsSA.png)

Then click `Save`:

![zip3](http://i.imgur.com/QJ0eM7X.png)

What do you see?

**Comment by ballsystemlord** [comment] 2015-02-16 19:55
Sorry, this was mostely due to me being used to the behavoir of w3mir which treates /downloads as ~/downloads and /home/me/downloads as ~/home/me/downloads.
However there IS still an issue here. Whenever I try to save a page from the ite squidi.net; for example:  http://www.squidi.net/threep/p166/
I get the message: "Error: Error downloading ... Server replied: Not Acceptable"
I'm talking hitting ctrl-s to download, not just viewing.
I can save the material with firefox.
Thanks

**Comment by ballsystemlord** [comment] 2015-02-16 22:41
Here's another one:
http://www.raphkoster.com/2006/08/28/do-classes-suck/

**Comment by JHooverman** [comment] 2015-02-17 19:56
This is the corresponding screenshot:

![etr](http://i.imgur.com/OOT5uQe.png)

Download works with FF and fails with both Qt4 + Qt5.

**Comment by The-Compiler** [comment] 2015-02-17 21:18
The culprit seems to be the `User-Agent: Mozilla/5.0` header sent with the request (for whatever weird reason). With that, I can also reproduce this using wget:

```
wget -O/dev/null --server-response --user-agent 'Mozilla/5.0' 'http://www.squidi.net/threep/p166/'
--2015-02-17 22:16:52--  http://www.squidi.net/threep/p166/                                           
Resolving www.squidi.net (www.squidi.net)... 192.254.185.55
Connecting to www.squidi.net (www.squidi.net)|192.254.185.55|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 406 Not Acceptable
  Server: nginx/1.6.2
  Date: Tue, 17 Feb 2015 21:16:53 GMT
  Content-Type: text/html; charset=iso-8859-1
  Content-Length: 226
  Connection: keep-alive
2015-02-17 22:16:53 ERROR 406: Not Acceptable.
```

Now I only wonder where this default is coming from... though I also can reproduce this in my own Qt based browser.

**Comment by The-Compiler** [comment] 2015-02-17 21:51
`Mozilla/5.0` is indeed the default set by Qt in `qtbase/src/network/access/qhttpnetworkconnection.cpp` (`QHttpNetworkConnectionPrivate::prepareRequest`). Setting a more sane value via `QNetworkRequest::setHeader(QNetworkRequest::UserAgentHeader, ...)` fixes the issue for me - though I don't really write C++, so I can't contribute the actual fix.

**Comment by ballsystemlord** [comment] 2015-03-30 15:21
Hello, I continueto use qupzilla frequently and I've discovered a different problem, it migh be related.
When downloading html pages from http://leoeditor.com/ via ctrl-s I get "Error: Error downloading XXXX - server replied: Not Acceptable".
I can brows the site, just not download the pages.
Thanks

**Comment by The-Compiler** [comment] 2017-02-07 20:24
This is probably not an issue anymore with QtWebEngine?

**Closed** 2017-02-07 20:25 UTC
Labels: Other
