### ISSUE TITLE
Tab loses content when closing parent tab

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#2277] opened 2017-03-23 19:00 UTC
I hope the title is clear? What I mean is that if I click a link that opens in a new tab and then close the tab that I came from, the tab with the link that I followed loses the page (i.e. it becomes an empty page with the tab title still intact). Refreshing doesn't bring it back. I have to open a new tab and open the link in there in order to get it back.
This problem is present in QupZilla for a while now.

OS: Solus (Linux)
QupZilla version: Latest Git Master
Qt version: 5.8.0

I hope this can be solved!

**Comment by Martii** [comment] 2017-03-23 19:15
Confirmed

**Comment by nowrep** [comment] 2017-03-23 21:18
Known bug in QtWebEngine 5.8

**Comment by Vistaus** [comment] 2017-03-24 10:28
@nowrep Thanks for the clarification! Do you know if this is fixed in the 5.9 beta?

**Comment by Martii** [comment] 2017-03-24 18:48
@Vistaus 

> Do you know if this is fixed in the 5.9 beta?

Linux... Doesn't appear to be but it is a beta. Recompiled d544a5dc5f75b2aa5158a232f731e35cae0c50e4 with it and retested.

@nowrep 
Is there a chance for a specific bug report url to go vote/watch on it? Yes I did do a search but there are several pages. Would be nice to narrow it down.

**Comment by Martii** [comment] 2017-03-25 08:16
Looks like https://bugreports.qt.io/browse/QTBUG-58634

**Comment by nowrep** [comment] 2017-03-25 09:32
https://bugreports.qt.io/browse/QTBUG-58381 Fixed in 5.9

**Closed by nowrep** 2017-03-25 09:32 UTC
Labels: QtWebEngine

**Comment by Martii** [comment] 2017-03-25 14:48
So... explanation needed please... since [the parent issue](https://bugreports.qt.io/browse/QTBUG-58381) says:

> Resolved:
    15/Mar/17 3:06 PM 

... and the test that I did [above](https://github.com/QupZilla/qupzilla/issues/2277#issuecomment-289112289) with the beta which is dated March 24, 2017...

I would have to guess the patch didn't make it to the beta that I just downloaded yesterday and compiled? :question:

**Comment by nowrep** [comment] 2017-03-25 14:52
Explanation: As you can see from the code review, the change was merged to `5.8` branch on March 15 and most likely wasn't merged into `5.9` branch before tagging 5.9-beta.

**Comment by Martii** [comment] 2017-03-25 15:00
Okay ... thanks. :) Will look a little deeper into their issue tracker and code source. Glad it's tagged as fixed and just need to wait for it in release instead of beta release.

**Comment by Vistaus** [comment] 2017-04-07 15:39
Well, so far so good with 5.9 regarding this bug. Will keep an eye on it.
