### ISSUE TITLE
Download manager problems

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1806] opened 2015-12-12 05:40 UTC
I'm having problems downloading pdf files, I think because they have names containing parens - e.g. "EligibilityNotice(1).pdf".  (They're results from the HealthCare.gov website.) I get an "Operation Canceled" message on them, although files without parens download successfully.
 
I'm also seeing that alternate file lines in the download manager window are blacked out.  I've attached a screenshot, and a copy of the user stylesheet I use. (It's intended to make all web sites display as white text on a black background, though as I'm no CSS expert, it's mostly trial & error.) I'm using version 1.8.9 on OpenSuSE Linux.

 Styling with Markdown is supported
Write Preview

![qz](https://cloud.githubusercontent.com/assets/14325193/11760420/174f8ede-a04f-11e5-942c-e0f24523fcf6.jpg)

[opera2mj.css.txt](https://github.com/QupZilla/qupzilla/files/60059/opera2mj.css.txt)

**Comment by JHooverman** [comment] 2015-12-12 10:21
Would you please provide a direct link to download the EligibilityNotice.pdf? Might it be, that you tried to download this file a second time unintentionally?

Unfortunately I am not able to help you regarding your stylesheet question.

**Comment by jamesqf** [comment] 2015-12-12 19:02
I can't give you a direct link, as it's a password-protected site with a lot of private info.  I'll see if I can reproduce it on some more public site.

I don't think I tried to download it a second time.  If I had, shouldn't the first attempt have downloaded the file?  It's not in my download directory.  I would think the desired behavior for this would be to report that the file already exists, and give options to overwrite, cancel, or download with a new name.

**Comment by cranes-bill** [comment] 2015-12-13 10:40
I'm also not css expert, and i'm not sure if i understood properly (due to my bad English), but if you want to change **Download Manager** style, that should be applied in desktop theme or QupZilla theme. I don't know if that can be integrated in the described css. I only know, how to do it in QupZilla theme.
Sorry for my bad English!

**Comment by JHooverman** [comment] 2015-12-13 14:29
@jamesqf: On [this](http://data.madisoncity.k12.al.us/Documents/Employment/) page you will find some files, that contain parens in their names. Would you please try to download them and let us know about the result?

**Comment by cranes-bill** [comment] 2015-12-13 17:35
By the way, latest master (dd1e8eb) does not decoding the percentages to me!

**Comment by jamesqf** [comment] 2015-12-13 18:47
@JHooverman: Humm... Those all seem to download correctly.  I wonder what the problem on the other site could be?  I'll try it again today, and maybe see if the problem happens with another browser.

@cranes-bill: I've been trying to write a theme, mostly so I can get the scroll bar to have visually distinct colors.  It's been pretty slow going, since I know little about CSS, and nothing at all about Qt.  I don't know how to find the names that would apply to various elements, so my colors get applied to horizontal scroll bars in subwindows, but not to the vertical scroll bar in the main window - like this:
![qz](https://cloud.githubusercontent.com/assets/14325193/11768593/cde599da-a186-11e5-9f4d-fd4666d1d0ca.jpg)

**Comment by cranes-bill** [comment] 2015-12-13 19:16
See [here](https://github.com/QupZilla/qupzilla-plugins/tree/master/themes) _Cyanotype_ & _Fergris_ themes. I included lot of Qt classes there, so you might find what you need. Also read [here](https://github.com/QupZilla/qupzilla/wiki/Themes)! Unfortunately **reference** & **examples** links are inactive.

**Comment by JHooverman** [comment] 2015-12-13 19:37
@cranes-bill: I have just fixed the broken links to references and examples. Thank you for letting me know.

**Comment by cranes-bill** [comment] 2015-12-13 19:41
And next one **QToolButtom documentation**, please!
Thank you, very much!

**Comment by JHooverman** [comment] 2015-12-13 19:54
@cranes-bill: Done!

**Comment by jamesqf** [comment] 2015-12-13 21:56
@cranes-bill: I did read the wiki article on themes, though not yet whatever's at the now-fixed links.  With the Cyanotype & Fengris themes, though, is there perhaps some way to actually download them as a .tgz file or something?  When I click on the main.css, it just tries to display the file (with line numbers added), and for some reason this is very slow & unresponsive.  5 seconds or more to respond to a page down, CPU usage on one core goes to 100%...

**Comment by cranes-bill** [comment] 2015-12-13 22:40
You can clone all plugins dir as follow:
`git clone git://github.com/QupZilla/qupzilla-plugins.git`

**Comment by jamesqf** [comment] 2015-12-14 02:34
Thanks.  I've taken a look at them, and they seem to be pretty much what I got from the themes that come with the installation.  None seem to do anything to change the appearance of the scrollbar on the main window.

This probably is not the place for this sort of discussion.  Can anyone suggest someplace better?  Google hasn't been much help...

**Comment by jamesqf** [comment] 2015-12-14 02:55
@JHooverman: Tried to download the EligibilityResults.pdf file with another browser, and it reported a file with that name already existed.  (From last year, guess I haven't given my drive a good cleanup lately.)  So it seems the parens in the name are qupzilla's attempt to write the file under a new name, but why that should fail is beyond me.

I do think it would be better to report the name clash, and ask whether to cancel, overwrite, or rename.

**Comment by cranes-bill** [comment] 2015-12-14 07:24
Aaah..., i thought that you want to change the library slider. The main window slider is from the desktop theme, so look at _YOUR_CURRENT_THEME/gtk-2.0/gtkrc_ and any other file in **gtk-2.0** directory. If you don't have this directory, your desktop theme does not support gtk2 style, which Qt actually uses.

**Comment by jamesqf** [comment] 2015-12-14 18:52
@cranes-bill: Well, that saves me from wasting more time trying to do it with a theme.  Of course the problem is that I don't actually have a "desktop" (other than the wooden object that my display sits on), I use a window manager (fvwm2).  So I don't know if it's going to be possible to do anything useful.

There is a .config/gtk-2.0 directory, but the only thing in it is a "gtkfilechooser.ini" file.  Maybe if I can find something on how to write a gtkrc file and drop it in there?

**Comment by JHooverman** [comment] 2015-12-14 19:19
@jamesqf: I have successfully downloaded the same file twice into the same directory. As expected (1) has been added to the filename:

![img1](http://i.imgur.com/0D0TpJk.png)

So, QupZilla will not overwrite an existing file having the same name as the downloaded one.

@jamesqf said:
_Tried to download the EligibilityResults.pdf file with another browser, and it reported a file with that name already existed. (From last year, guess I haven't given my drive a good cleanup lately.) So it seems the parens in the name are qupzilla's attempt to write the file under a new name, but why that should fail is beyond me._

@jamesqf: Might it be, that the exisiting file `EligibilityResults.pdf`, that you have downloaded with another browser belongs to another user or you do not have write access to this file?

**Comment by cranes-bill** [comment] 2015-12-14 19:42
@JHooverman, on your picture the file names are with the percentages as well, that what i noticed [early](https://github.com/QupZilla/qupzilla/issues/1806#issuecomment-164279277), but should be decoded. May be i need to open a new issue about that?

@jamesqf, [Here](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Using_a_GTK.2B_icon_theme_in_Qt_apps) you can red a bit more about configuration, and [here](http://gnome-look.org/index.php?xcontentmode=100) for example, you can download some themes.

**Comment by JHooverman** [comment] 2015-12-14 19:51
@cranes-bill: Which QupZilla version are you using?

**Comment by cranes-bill** [comment] 2015-12-14 20:03
Any one possible :smile:
But this only occurs with `master` branch to me. With `v1.8` - Qt4 & `v1.8` - Qt5.5, the file names are „normal“.

**Comment by JHooverman** [comment] 2015-12-14 20:39
@cranes-bill: Done! I will not refer to this issue because it has nothing to do with it.

**Comment by cranes-bill** [comment] 2015-12-14 21:04
Sure, thank you very much! You help me a lot with that, because i must not search a readable sentences to explain the problem properly in English.
Just one more think (to make a quite mess in this threat):
About [this](https://github.com/QupZilla/qupzilla/issues/1807#issuecomment-164261135) my question, can you check please, when you go to **Menu:** -> **View** -> **Character Encoding** -> **IBM**, if showing list is scrollable, can you scroll with the mouse scroller over it?

**Comment by jamesqf** [comment] 2015-12-14 22:18
JHooverman : No, both files belong to me, and have the same permissions (except for the read permission for others, which shouldn't matter:

    ll E*
    -rw-r----- 1 me users 133541 Dec 14  2014 EligibilityNotice2014.pdf
    -rw-r--r-- 1 me users 192756 Dec 13 18:49 EligibilityNotice.pdf
    t61/home/me> 

I did rename the 2014 fiile to remove the name clash.

**Comment by JHooverman** [comment] 2015-12-16 17:54
@cranes-bill: I am not able to scroll over it (Sorry, for my late reply).

**Comment by JHooverman** [comment] 2015-12-16 17:58
@jamesqf: Since your issue seems not to be reproducible (we created and verified two test cases), I am going close it now. If you have new information or a reproducible test procedure, them please re-open. Thank you.

**Closed by JHooverman** 2015-12-16 17:58 UTC
Labels: Waiting for feedback

**Comment by cranes-bill** [comment] 2015-12-16 21:02
@JHooverman 
So that's a bug, but perhaps Qt5 related...
Thank you!
