### ISSUE TITLE
Unable to open bugreports.qt-project.org (Untrusted connection)

### ISSUE THREAD

**Issue by SafaAlfulaij** [QupZilla/qupzilla#1580] opened 2015-01-03 06:28 UTC
As in title, A webpage with:
> Untrusted connection
>Check the address for typing errors such as ww.example.com instead of www.example.com
>If you are unable to load any pages, check your computer's network connection.
>If your computer or network is protected by a firewall or proxy, make sure that
QupZilla is permitted to access the Web.
>[Try Again]

comes up. I've tried all the options in Preferences -> Privacy -> Certificate Manager but no change

**Comment by cranes-bill** [comment] 2015-01-03 07:00
The same as [here](https://github.com/QupZilla/qupzilla/issues/1579) to me. (works with Qt 4)

**Comment by JHooverman** [comment] 2015-01-03 09:39
Closing this issue as a duplicate of #1579.

**Closed by JHooverman** 2015-01-03 09:39 UTC
Labels: Duplicate
