### ISSUE TITLE
Favicon Not Appearing

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1474] opened 2014-09-28 00:25 UTC
In 1.8.0 in Linux I noticed some Favicon doesn't appear in the addressbar or tab. 

Also In Firefox if it only appers to show in the Tab, then it will appear in the Firefox bookmarks, in QupZilla it doesn't appear in the bookmarks when they only appear in the Firefox tab...

Also when importing bookmarks from Firefox shouldn't the favicon be imported too? Because it's not...

**Comment by MttCastelli** [comment] 2016-01-23 13:59
![quozilla_miss_fav](https://cloud.githubusercontent.com/assets/11462157/12530515/a5cc344c-c1e1-11e5-92c2-647525a4c335.jpg)
Hi, this is happening to me again: Qupzilla 1.8.9 from PPA and dev Ubuntu Xenial.

Regards

**Comment by nowrep** [comment] 2016-01-23 14:00
You must first visit that site before the favicon is saved.

**Comment by MttCastelli** [comment] 2016-01-23 14:08
My favicons disappeared after some update of I-do-not-know-what.

**Comment by MttCastelli** [comment] 2016-02-27 15:54
@nowrep David can you answer, please. These could regard any Ubuntu users upgrading to xenial ASA it will be released. Is there any missing dependencies maybe? 
I've also tried to delete qupzilla folders in home .config an .cache, this wont fix.

**Comment by nowrep** [comment] 2016-02-27 15:56
And the issue is favicons never being displayed or being forgotten after some time?

**Comment by MttCastelli** [comment] 2016-02-27 16:16
The issue is favicons are not displayed and not saved in bookmarks bar, but they are in the tabs.

**Comment by nowrep** [comment] 2016-02-27 16:17
Any interesting info when running `qupzilla` in terminal?

**Comment by MttCastelli** [comment] 2016-02-27 16:25
`$ qupzilla 
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "Method \"GetDevices\" with signature \"\" on interface \"org.freedesktop.NetworkManager\" doesn't exist\n"
"Object path cannot be empty"
SpellCheck: Language = "it_IT" "ISO-8859-15"`

**Comment by MttCastelli** [comment] 2016-02-27 16:29
And this on the closure:
`load glyph failed err=6 face=0x74fd400, glyph=2797`

**Comment by nowrep** [comment] 2016-02-27 17:03
Looks fine, can you inspect `browsedata.db` in your profile dir and check if there are icons in *icons* table?

It is SQLite database, so you'll need some app to browse it (eg. sqlitebrowser).

**Comment by MttCastelli** [comment] 2016-02-27 18:00
ok, there are 10818 icons

**Comment by nowrep** [comment] 2016-02-27 20:27
That should be fine. Try to delete all data from `icons` table:

```sql
DELETE FROM icons
```

**Comment by MttCastelli** [comment] 2016-02-28 11:54
Done, than i launched qupzilla and tried some bookmarks: no change. But it was predictable I guess because as I said "I've also tried to delete qupzilla folders in home .config an .cache, this wont fix."

**Comment by tsujan** [comment] 2016-05-05 16:52
This is happening to me too with Qupzilla-1.8.9 from the Debian repository. The same version shows favicons correctly on Manjaro/Arch. Downstream issue?

**Comment by sanette** [comment] 2016-12-19 20:59
I also have the same problem with Qupzilla-1.8.9 from Mint repository
(Mint KDE 18 is based on ubuntu 16.04)
Icons appear on tabs, but not on the bookmarks toolbar (*none* of them).

package is 1.8.9~dfsg1-3 from xenial/universe amd64 Packages

**Comment by tsujan** [comment] 2016-12-19 21:04
Oh, I forgot to add that favicons are OK in v2.0.99 :)

**Comment by sanette** [comment] 2016-12-19 21:40
how to try v2.0.99? is there a build somewhere for ubuntu?

**Comment by tsujan** [comment] 2016-12-19 21:59
@sanette, unfortunately Debian and its derivatives (including Ubuntu) don't have QtWebEngine, which is required for newer versions of QupZilla. It isn't likely that Debian provides its users with QtWebEngine in the near future.

**Comment by tsujan** [comment] 2016-12-25 10:01
Good news: QtWebEngine has entered Debian sid. So, it's just a matter of time until it appears in Ubuntu.

**Comment by mysticfall** [comment] 2017-08-26 00:59
I'm having the same problem with Qupzilla 2.0.2 on Kubuntu devel. I tried to a few websites to the bookmark toolbar and visit them multiple times by clicking the buttons, but the favions never got updated.

Should we reopen this issue, or is there a new one that I can subscribe to?

**Comment by mysticfall** [comment] 2017-08-26 01:24
@tsujan But I'm having this problem with a package version of _Qupzilla_ when I tested with a clean profile. Is there anything I can do to verify that it's not an issue with the package itself?

**Comment by cranes-bill** [comment] 2017-08-26 04:46
@mysticfall, you are using unmaintained QupZilla version, so you should not open enithing!

**Comment by mysticfall** [comment] 2017-08-26 04:50
@cranes-bill Huh? Are you saying that _Qupzilla 2.1.2_ that I installed via apt-get is an unmaintained version?

```dpkg -s qupzilla
Package: qupzilla
Status: install ok installed
Priority: extra
Section: web
Installed-Size: 4756
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.1.2~dfsg1-2ubuntu2
Provides: www-browser
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.9.0~beta), libqt5webenginecore5 (>= 5.7.1), libqt5widgets5 (>= 5.0.2), libqupzilla1 (= 2.1.2~dfsg1-2ubuntu2), libstdc++6 (>= 5), libqt5sql5-sqlite
Description: lightweight web browser based on libqtwebkit
 QupZilla is a new and very fast QtWebKit browser. It aims to be a
 lightweight web browser available through all major platforms. This
 project has been originally started only for educational
 purposes. But from its start, QupZilla has grown into a feature-rich
 browser.
 .
 QupZilla has all standard functions you expect from a web browser. It
 includes bookmarks, history (both also in sidebar) and tabs. Above
 that, you can manage RSS feeds with an included RSS reader, block ads
 with a builtin AdBlock plugin, block Flash content with Click2Flash
 and edit the local CA Certificates database with an SSL Manager.
 .
 QupZilla's main aim is to be a very fast and very stable QtWebKit
 browser available to everyone.
Homepage: http://www.qupzilla.com/
Original-Maintainer: Georges Khaznadar <georgesk@debian.org>```

**Comment by cranes-bill** [comment] 2017-08-26 04:54
Not i, you just saying that in your [comment](https://github.com/QupZilla/qupzilla/issues/1474#issuecomment-325067015) above!

![capture du 2017-08-26 07 53 59](https://user-images.githubusercontent.com/5161278/29738709-c3da17e4-8a33-11e7-8042-c4d9a72f84d5.png)

**Comment by mysticfall** [comment] 2017-08-26 05:03
@cranes-bill Ok, I edited my post to change the typo. So, are you going to be so kind to let me know how to solve the actual issue now?

**Comment by tsujan** [comment] 2017-08-26 09:53
@mysticfall There may be a difference: my installed QupZilla is always compiled against the latest qtwebengine -- currently 5.9.1. So, if QupZilla is compiled against an older version of qtwebengine in your case, that might be the cause.

**Comment by mysticfall** [comment] 2017-08-26 10:03
@tsujan Thanks for the suggestion. I just checked the version of my `libqt5webengine5` and it says `5.9.1+dfsg-2ubuntu1`.

**Comment by tsujan** [comment] 2017-08-26 10:17
> I just checked the version of my libqt5webengine5 and it says 5.9.1+dfsg-2ubuntu1.

Then I have no clue because qupzilla and qt5webengine are both up-to-date in your case. We have the same versions and yet all favorite icons are OK here. A member of the development team might have an answer.

**Comment by tsujan** [comment] 2017-08-26 10:20
Oh, my last suggestion: Help → About QupZilla. Here, it says:

Application version 2.1.2
QtWebEngine version 5.9.1

**Comment by mysticfall** [comment] 2017-08-26 10:25
Unfortunately, I see the the same message when I click the _About_ menu. Probably there's something wrong with the _Ubuntu_ package, as I have the same problem both in 2 different computers.

Thanks for the help though :)

**Comment by loimu** [comment] 2017-11-01 11:57
Launchpad Janitor (janitor) wrote on 2017-08-27:	#1

**Comment by loimu** [comment] 2017-11-01 11:57
https://bugs.launchpad.net/ubuntu/+source/qupzilla/+bug/1713223

**Comment by cranes-bill** [comment] 2017-11-12 11:02
@nowrep, i also got that issue after installing self compiled Qt 5.9.2 (finally :smiley:), but i resolved the problem when i replaced the _Data Type_ in `icon` _column_ in `icons` table from **TEXT** to **BLOB**.
Looks like the problem is probably Sqlite versions inconsistency. I hope that will help to others who are facing this problem.

**Comment by loimu** [comment] 2017-11-12 19:59
Wasn't able to reproduce this successful result, no matter with index or not (using system Qt)
So I guess it's not the case

**Comment by nowrep** [comment] 2017-11-12 20:13
That index has to be there, so even if it actually did fix the issue (very unlikely), it can't be used.

**Comment by cranes-bill** [comment] 2017-11-12 21:26
_Very unlikely,_ but fact....
I don't claim that the index must not be there, i just was hoping that might be a clue to investigate the problem (which are in system  sqlite libraries).
I tried almost all variants, but only this one are working for me.

**Comment by loimu** [comment] 2017-11-13 06:29
@nowrep but don't you think that storing an icon for each url(!) is a bit overkill? I ended up having ~50k icons stored in the database. Having only hostname should suffice

**Comment by cranes-bill** [comment] 2017-11-13 08:15
Also works for me if i add second column to `iconsUrl` index... :fearful:

**Comment by nowrep** [comment] 2017-11-13 08:37
@loimu No, I don't see a problem with it, each different URL may have different favicon and on top of it the favicon for one URL may not even be static. The issue however is, that it is not correctly deleted with deleting history entries (`icons` and `history` entries should be linked instead).

@cranes-bill Can you please post database schema (`.schema` sqlite command) for working and not working database?

**Comment by loimu** [comment] 2017-11-13 08:54
> favicon for one URL may not even be static

@nowrep 
Sure that's the way it is. But what's the point of storing it anyway if it changes all the time? Favicon should be recognizable. Means it's not supposed to change very often.

**Comment by nowrep** [comment] 2017-11-13 08:57
@loimu To show the correct icon for each history entry, that's it ...

**Comment by cranes-bill** [comment] 2017-11-13 09:03
Sure, here are the both schemes:

### The original one (not working):
```
CREATE TABLE autofill_exceptions (id INTEGER PRIMARY KEY, server TEXT);
CREATE TABLE autofill (data TEXT, id INTEGER PRIMARY KEY, password TEXT, server TEXT, username TEXT, last_used NUMERIC);
CREATE TABLE icons (icon TEXT, id INTEGER PRIMARY KEY, url TEXT);
CREATE TABLE history (title VARCHAR(200), count NUMERIC, id INTEGER PRIMARY KEY, date NUMERIC, url VARCHAR(256));
CREATE TABLE search_engines (id INTEGER PRIMARY KEY, name TEXT, icon TEXT, url TEXT, shortcut TEXT, suggestionsUrl TEXT, suggestionsParameters TEXT, postData TEXT);
CREATE TABLE autofill_encrypted (data_encrypted TEXT, id INTEGER PRIMARY KEY,password_encrypted TEXT, server TEXT, username_encrypted TEXT, last_used NUMERIC);
CREATE INDEX autofillServer ON autofill(server ASC);
CREATE INDEX autofillExceptionServer ON autofill_exceptions(server ASC);
CREATE INDEX historyTitle ON history(title ASC);
CREATE INDEX autofillEncryptedServer ON autofill_encrypted(server ASC);
CREATE UNIQUE INDEX iconsUrl ON icons(url ASC);
CREATE UNIQUE INDEX historyUrl ON history(url ASC);
```

### The changed one (working):
```
CREATE TABLE autofill_exceptions (id INTEGER PRIMARY KEY, server TEXT);
CREATE TABLE autofill (data TEXT, id INTEGER PRIMARY KEY, password TEXT, server TEXT, username TEXT, last_used NUMERIC);
CREATE TABLE icons (icon TEXT, id INTEGER PRIMARY KEY, url TEXT);
CREATE TABLE history (title VARCHAR(200), count NUMERIC, id INTEGER PRIMARY KEY, date NUMERIC, url VARCHAR(256));
CREATE TABLE search_engines (id INTEGER PRIMARY KEY, name TEXT, icon TEXT, url TEXT, shortcut TEXT, suggestionsUrl TEXT, suggestionsParameters TEXT, postData TEXT);
CREATE TABLE autofill_encrypted (data_encrypted TEXT, id INTEGER PRIMARY KEY,password_encrypted TEXT, server TEXT, username_encrypted TEXT, last_used NUMERIC);
CREATE INDEX autofillServer ON autofill(server ASC);
CREATE INDEX autofillExceptionServer ON autofill_exceptions(server ASC);
CREATE INDEX historyTitle ON history(title ASC);
CREATE INDEX autofillEncryptedServer ON autofill_encrypted(server ASC);
CREATE UNIQUE INDEX historyUrl ON history(url ASC);
CREATE UNIQUE INDEX iconsUrl ON icons(id, url);
```

**Comment by nowrep** [comment] 2017-11-13 09:07
What about leaving the sort order?

```
CREATE UNIQUE INDEX historyUrl ON history(url);
```

**Comment by cranes-bill** [comment] 2017-11-13 09:23
I already did that or changed it to `DESC`, but without success. Looks like the system query has problem to decode the url record, when it's not plain text. See the following table dump please, where the icon for **https://www.qupzilla.com/** is showed, but the others are not:

```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE icons (icon TEXT, id INTEGER PRIMARY KEY, url TEXT);
INSERT INTO "icons" VALUES(X'89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF61000000097048597300000EC400000EC401952B0E1B0000022449444154388D8D53316B144114FEE6BDDDDC26DEEEDDEEDE110376826021589E1A8D58062C6C048B14B6F9073696829DA24550C1228529446C6C4513C5C246B0D6200A89C9DDEDDC919CB9DB997916B90D4B4093AF7AF3F8BEEF7DF3865138847ABD7E85996F01B8A64466004094DA00F0D65AFB426BBD5AE6AB52CD8D387ECE9EB770D8B40C6BCC723BCB6E03B065034ED374CD23BAF03F7101E3DCA74EA7731980650068C4F1B2C73C9F1BB33ACAF39BDD2CDB20E653A4D4B6887404A86EB7DB7746797ED7F3BC333EF3EC64A5727AB0B7F70A5114B5A69B4D996E36254992A5F1902A80A9D2D06A91364992A5821F45518B2698170FEE67EDB371B903605032D8012000E09C5B299A13CC8B04E65900B0CE8D00748EB18275EBDC707F733C4B183F1594DAECF57AEB47A9B5D63FA0D46F0080C80C15D100D400D031121044EAE35A48809F00C04AD5D234BD7E943A8EE379268AB03FF91791526B4E045BEDB675C6BC8CC3F0D2BFC449185E64A2A7C55944DE516ECCE3D130878858DDEFF77BBBBB1F8868104551AB200641709588B6FD20F8C844274B068F486BFDC5AFF84FA69BCD89BAEFCF55ABD585300C3F2BA5B60A62A552D989A2A8514E63451E6459F6F5E02F2471FC9E88CE59E7CE8B485F6BAD4BFCB091A69B4C340500D698D7ED2CBBB1BFD131BA593607A55698E8BBC7FC0DC04CC9E0442136C6DC2BC400C0E55883C1E0CD6410EC41A986EFFBCBC3E1F00F00D46A355F899C75C0C34EB77BBFACF90B25EEDA05D7C7D5360000000049454E44AE426082',1,X'68747470733A2F2F6769746875622E636F6D2F5175705A696C6C612F7175707A696C6C612F697373756573');
INSERT INTO "icons" VALUES(X'89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF61000000097048597300000EC400000EC401952B0E1B0000022449444154388D8D53316B144114FEE6BDDDDC26DEEEDDEEDE110376826021589E1A8D58062C6C048B14B6F9073696829DA24550C1228529446C6C4513C5C246B0D6200A89C9DDEDDC919CB9DB997916B90D4B4093AF7AF3F8BEEF7DF3865138847ABD7E85996F01B8A64466004094DA00F0D65AFB426BBD5AE6AB52CD8D387ECE9EB770D8B40C6BCC723BCB6E03B065034ED374CD23BAF03F7101E3DCA74EA7731980650068C4F1B2C73C9F1BB33ACAF39BDD2CDB20E653A4D4B6887404A86EB7DB7746797ED7F3BC333EF3EC64A5727AB0B7F70A5114B5A69B4D996E36254992A5F1902A80A9D2D06A91364992A5821F45518B2698170FEE67EDB371B903605032D8012000E09C5B299A13CC8B04E65900B0CE8D00748EB18275EBDC707F733C4B183F1594DAECF57AEB47A9B5D63FA0D46F0080C80C15D100D400D031121044EAE35A48809F00C04AD5D234BD7E943A8EE379268AB03FF91791526B4E045BEDB675C6BC8CC3F0D2BFC449185E64A2A7C55944DE516ECCE3D130878858DDEFF77BBBBB1F8868104551AB200641709588B6FD20F8C844274B068F486BFDC5AFF84FA69BCD89BAEFCF55ABD585300C3F2BA5B60A62A552D989A2A8514E63451E6459F6F5E02F2471FC9E88CE59E7CE8B485F6BAD4BFCB091A69B4C340500D698D7ED2CBBB1BFD131BA593607A55698E8BBC7FC0DC04CC9E0442136C6DC2BC400C0E55883C1E0CD6410EC41A986EFFBCBC3E1F00F00D46A355F899C75C0C34EB77BBFACF90B25EEDA05D7C7D5360000000049454E44AE426082',2,X'68747470733A2F2F6769746875622E636F6D2F5175705A696C6C612F7175707A696C6C612F77696B69');
INSERT INTO "icons" VALUES(X'89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF61000000097048597300000EC400000EC401952B0E1B0000020249444154388D8D93B14BD47118C63FCFD79FDC090A927711D4E0E0E01A39B48427080919062128787227858BD01AB43804FD0346087177E985810549060D0E17D5DED0E0E0D0E020DD1582834AD7EF69E84E8EA3B477FAF2FDBECFF33EEFF37E5FD116E7B285EB1D0A77C0A342BD00C6FBA02DC7946AE5DCDBD67C350F3DD3CBA96494284A8CB793B686CDE651FD387FB0365F3B21E8995E4E253B131F0483A7814F4860FBE8E7F1B583B5F95A04908C1245E17ECCEB187D94E21A0E03E021890C28D9267B3019258A077053A999D28D10D88C1D676AAB73EFDBABA5271F77D3D5751B870589A1D6B7BAE331A5674BEBE081EA4AFEF259D253D9C2B0D0A2A44CA3959751C3EDA7A72233C5E4F98BBA62189054B1E3234963E0D148A83726DEF967458705058F0349352C94D4F042BD11801CEAADC0DEA9627F67274F40DD0E711987BAE45BED660244C6FB924EC6D7375B9808D692CDFD5A39F7BC71BD9C9E2C5E20E9479272CD5CE3FD00DAB2B90A909E7D762F3894ADF845081A48674B0F52D9C23040753DBF575DCDE7E33A43B62B7F28B4753246C39260E16F5E187F56AC87DF76BF6E5059AC379562F60490CE96DE9CF585016C76252AA09D7AEC2F3FCAB957018023DF356C9F4520710998319EEA38F62780D0EC8F438FD87EF71F2A3639F448753DBF072DDBD88CBED9C2448795B3C8B4AEB34CE5975CFABE32B7D19AFF1BF377D08075973F200000000049454E44AE426082',3,'https://www.qupzilla.com/');
INSERT INTO "icons" VALUES(X'89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF61000000097048597300000EC400000EC401952B0E1B0000027849444154388D85534D4C1351189CB7BBB86DA13516A342B060699372212188A8AD6022A146D4832723462F1C107A2031311E340A895E25BA45BD7000510E62BC48C0839A16C182187F63427F40120A890565A9B46BB7FB3C60EB666D746E2F9999F7FDCC47A081CD4B8FC9E2526B22E473D154C20400244F2F1AECF57ECEB8BD37D84E1EA9F944FDB0740603D26C600F5564ADEF0699E1C0EFAA9D9CBF62AFFDCBA0C833B29C1697CC84E10000942A0055721AB1A61D2B8BC2E1420060323F2BF198D9E0687C4EF27482DED1D0C1EFAC1AD4D9EAFD84DD848C69066971C96CE90C060080D8BDF484383D3854507DD2196E27E3B97EB45C9DB9A0FC5869497D0DD933ED118683B1A6F938B15C5B1891636147F4465D59CE7A55B0F5D0BD52F4E34D697EBA06000C15EE612619F6D5B37AE3E4FFC4E5B7A8F3E7C28783899967EF0C15EE610048847C2E8E28691D95E54FB944D61EDA945E9EBB9C8C4CD4C6A70736066828C4FAE75100004D254C0C00303A63522B2EB9F83A2845C6EFA462B3C3868AC6A7200CA82243BB628E326C5249ADEF56F5793AFEE6613F5F5ADD1A3E47EEAAC965DDF12789B78F8F640799A717199DD5E9A3943A00C02ED04B6B530FFAF32B8F5E5F7DE1756E3BDB77CF2AD0431983B98E82A6FCEAE64ABEA4EA3D6138E86D75631B6B9C1A182AA86916D626FB3DA00A401810C2FC29D35CFA85B7BABA221ED29BAD54905B28CB2E130028ED0ABF4A84FCD978E602613880377ECF7734F857FDB7A5CD0DE75F46DA487736CAC59ED1982C2E16FECB2403D658B4B6E8759B80DF510680A8E0DEAA2BDF3FA58DADB60ABDED4020230634D70800F61E7A4AFA163D2345C6F6A9CF99B7BA26F82DC57DC136725FCDFF05490AFD80EDC44FE50000000049454E44AE426082',4,X'687474703A2F2F626C6F672E7175707A696C6C612E636F6D2F');
INSERT INTO "icons" VALUES(X'89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF61000000097048597300000EC400000EC401952B0E1B0000022449444154388D8D53316B144114FEE6BDDDDC26DEEEDDEEDE110376826021589E1A8D58062C6C048B14B6F9073696829DA24550C1228529446C6C4513C5C246B0D6200A89C9DDEDDC919CB9DB997916B90D4B4093AF7AF3F8BEEF7DF3865138847ABD7E85996F01B8A64466004094DA00F0D65AFB426BBD5AE6AB52CD8D387ECE9EB770D8B40C6BCC723BCB6E03B065034ED374CD23BAF03F7101E3DCA74EA7731980650068C4F1B2C73C9F1BB33ACAF39BDD2CDB20E653A4D4B6887404A86EB7DB7746797ED7F3BC333EF3EC64A5727AB0B7F70A5114B5A69B4D996E36254992A5F1902A80A9D2D06A91364992A5821F45518B2698170FEE67EDB371B903605032D8012000E09C5B299A13CC8B04E65900B0CE8D00748EB18275EBDC707F733C4B183F1594DAECF57AEB47A9B5D63FA0D46F0080C80C15D100D400D031121044EAE35A48809F00C04AD5D234BD7E943A8EE379268AB03FF91791526B4E045BEDB675C6BC8CC3F0D2BFC449185E64A2A7C55944DE516ECCE3D130878858DDEFF77BBBBB1F8868104551AB200641709588B6FD20F8C844274B068F486BFDC5AFF84FA69BCD89BAEFCF55ABD585300C3F2BA5B60A62A552D989A2A8514E63451E6459F6F5E02F2471FC9E88CE59E7CE8B485F6BAD4BFCB091A69B4C340500D698D7ED2CBBB1BFD131BA593607A55698E8BBC7FC0DC04CC9E0442136C6DC2BC400C0E55883C1E0CD6410EC41A986EFFBCBC3E1F00F00D46A355F899C75C0C34EB77BBFACF90B25EEDA05D7C7D5360000000049454E44AE426082',5,X'68747470733A2F2F6769746875622E636F6D2F5175705A696C6C612F7175707A696C6C61');
CREATE UNIQUE INDEX iconsUrl ON icons(url ASC);
COMMIT;
```

**Comment by nowrep** [comment] 2017-11-13 09:33
Hmm, not here ... what about changing `url` type to `VARCHAR(256)` ?

**Comment by nowrep** [comment] 2017-11-13 09:38
`PRAGMA encoding="UTF-8";` ?

**Comment by cranes-bill** [comment] 2017-11-13 09:45
> PRAGMA encoding="UTF-8"; ?

Sadly, nope. :disappointed:

**Comment by nowrep** [comment] 2017-11-13 09:48
```diff
diff --git a/src/lib/tools/iconprovider.cpp b/src/lib/tools/iconprovider.cpp
index 4afa2b01..b777215b 100644
--- a/src/lib/tools/iconprovider.cpp
+++ b/src/lib/tools/iconprovider.cpp
@@ -259,7 +259,7 @@ void IconProvider::saveIconsToDatabase()
         buffer.open(QIODevice::WriteOnly);
         ic.second.save(&buffer, "PNG");
         query.bindValue(0, buffer.data());
-        query.bindValue(1, encodeUrl(ic.first));
+        query.bindValue(1, QString::fromUtf8(encodeUrl(ic.first)));
 
         SqlDatabase::instance()->execAsync(query);
     }
```

**Comment by cranes-bill** [comment] 2017-11-13 10:34
It is much beter now (**FOR NEW CREATED DATABASE**). But still not showing icons for:
```
https://github.com/QupZilla/qupzilla/wiki
https://github.com/QupZilla/qupzilla/issues
```

For **OLD DATABASE** has improvement as well, but in `COMPLETER` for example still the same (i must do more tests)

**Comment by nowrep** [comment] 2017-11-13 10:36
That would affect only newly saved icons, so I take it as this fixes the issue.

**Comment by cranes-bill** [comment] 2017-11-13 10:39
I agree...

**Closed** 2017-11-13 10:42 UTC
Labels: Waiting for feedback
