### ISSUE TITLE
Coub.com crashes

### ISSUE THREAD

**Issue by JuPlutonic** [QupZilla/qupzilla#2176] opened 2017-01-23 18:50 UTC
Openning any video on coub.com causes qupzilla crash.
Example:  http://coub.com/view/pr6ci
[coub.com-Crash-2017-01-22T22:17:52.txt](https://github.com/QupZilla/qupzilla/files/724640/coub.com-Crash-2017-01-22T22.17.52.txt)
[Crash-2017-01-23T16:31:40.txt](https://github.com/QupZilla/qupzilla/files/724641/Crash-2017-01-23T16.31.40.txt)

Linux: x86, 4.6.0-40-bfq #201607112209-Ubuntu, Ubuntu 14.04
QupZilla: 2.0.2 version QtWebEngine 5.7.1
Flash versions installed:
    pepperflashplugin-nonfree_1.3ubuntu1_i386
    browser-plugin-freshplayer-pepperflash (0.3.6-1\~webupd8\~trusty6)
Pepper enabled.

**Comment by iondissonance** [comment] 2017-01-23 22:22
Can't reproduce.

**Comment by JuPlutonic** [comment] 2017-01-25 21:47
Excuse me 5% of coub videos on coub.com can crash the engine:
http://coub.com/view/flzzp

[Crash-2017-01-25T22:42:30.txt](https://github.com/QupZilla/qupzilla/files/731008/Crash-2017-01-25T22.42.30.txt)

**Comment by JuPlutonic** [comment] 2017-01-27 10:01
When I added cookies, Reek AntiAdblock list, GreaseMonkey & Status bar Icons tuned on QupZilla: 2.0.2 version QtWebEngine 5.8.0 - crashes on coub.com previously didn't occurred start to take place again.
1) Sometimes if sQupzilla is main browser (update-alternatives ... x-www-browser) and you call from OS url like  http://coub.com/view/pr6ci / https://gemfury.com/
2) Sometimes if you go through coub.com lists like "best 2016" and after 2-3 minutes open one of autoplaying videos in another tab by clicking on video's title
[Crash-2017-01-27T09:53:55.txt](https://github.com/QupZilla/qupzilla/files/734891/Crash-2017-01-27T09.53.55.txt)
[Crash-2017-01-27T09:54:05.txt](https://github.com/QupZilla/qupzilla/files/734890/Crash-2017-01-27T09.54.05.txt)
[Crash-2017-01-27T09:57:08.txt](https://github.com/QupZilla/qupzilla/files/734889/Crash-2017-01-27T09.57.08.txt)

**Comment by nowrep** [comment] 2017-01-27 10:03
Can you please get backtrace with GDB (and QupZilla in debug mode)?

**Comment by JuPlutonic** [comment] 2017-01-27 10:04
Ok, gdb installed...

**Comment by JuPlutonic** [comment] 2017-01-27 10:15
[segfault on open url from os.txt](https://github.com/QupZilla/qupzilla/files/734916/segfault.on.open.url.from.os.txt)

**Comment by nowrep** [comment] 2017-01-27 10:16
Type `bt` and press <kbd>Enter</kbd> after it crashes. Also this looks like `QtWebEngineProcess` crashed.

**Comment by JuPlutonic** [comment] 2017-01-27 10:41
gdb's backtrace + bt:
[segfault on open url from os.txt](https://github.com/QupZilla/qupzilla/files/734988/segfault.on.open.url.from.os.txt)

**Comment by nowrep** [comment] 2017-01-27 10:44
This should be fixed in `master`, can you build it and confirm?

**Comment by JuPlutonic** [comment] 2017-01-27 13:59
[uncaught.ype.error.on.open.url.from.os.txt](https://github.com/QupZilla/qupzilla/files/735375/uncaught.ype.error.on.open.url.from.os.txt)
No crash, but you have to refresh 404 page to get into http://coub.com/view/pr6ci

**Comment by nowrep** [comment] 2017-01-27 14:07
Because the web process crashed, there's nothing to do in QupZilla about it.

**Comment by JuPlutonic** [comment] 2017-01-27 14:22
Ok

**Comment by nowrep** [comment] 2017-01-27 14:45
It should be reported upstream.

**Closed by nowrep** 2017-01-27 14:45 UTC
Labels: QtWebEngine
