### ISSUE TITLE
“Network access is disabled.”

### ISSUE THREAD

**Issue by ke7ofi** [QupZilla/qupzilla#1745] opened 2015-11-04 18:50 UTC
When I try to load a page (in this example, DuckDuckGo) after suspending (I assume the issue is reconnecting to the internet.), I get the following message.

![failed_loading_page](https://cloud.githubusercontent.com/assets/5540140/10948399/470a6548-82e2-11e5-9843-4729e3dde8b1.png)

Restarting QupZilla solves the problem, but it's quite irritating. Is there something wrong in my settings, or is this a bug?

**Comment by ltworf** [comment] 2015-11-04 19:38
I have the same issue

**Comment by ltworf** [comment] 2015-11-04 19:38
I am using wicd as network manager.

**Comment by ke7ofi** [comment] 2015-11-04 20:12
If it matters, I'm using nm.

**Comment by nowrep** [comment] 2015-11-04 20:43
Duplicate of #1744

**Closed by nowrep** 2015-11-04 20:43 UTC
