### ISSUE TITLE
any way to use "9" for "PageUp"?

### ISSUE THREAD

**Issue by sitaramc** [QupZilla/qupzilla#1687] opened 2015-07-23 01:44 UTC
or indeed any other single printable character?

(My keyboard sucks; pageup requries a "Fn" combo.  I'll rant about that some other time.  Shift-Space also works but is also 2 keys to press.)

Thanks!

**Comment by nowrep** [comment] 2015-10-02 15:29
Right now, you can just patch it to add shortcut for <kbd>9</kbd>.

Duplicate of #695

**Closed by nowrep** 2015-10-02 15:29 UTC
Labels: Duplicate

**Comment by sitaramc** [comment] 2015-10-02 17:39
Would it be possible for someone to give me a hint?

I am not really a C++ guy, leave along Qt.  I do see than a #define for ADD_ACTION but I have no idea what parameters to pass it to make a mapping for "PageDown", since PageDown isn't even in the standard menu.
