### ISSUE TITLE
Cannot load any website after network change

### ISSUE THREAD

**Issue by Nicky726** [QupZilla/qupzilla#1885] opened 2016-03-16 23:14 UTC
With QupZilla running and some websites openned suspend a computer and move to a destination with a different network (ehternet -> wifi, or a different wifi). After resume and network change try either refreshing some already loaded website or loading other website and observe not being able to load any with a general "cannot access website" error. After restarting QupZilla all websites are correctly loaded.

On Arch Linux with QupZilla 1.8.9 (WebKit 538.1) using NetworkManager for network connection. So far encountered on every network change from like 3 network changes.

**Comment by ke7ofi** [comment] 2016-03-18 21:54
This is a duplicate of #1744, #1750, and #1845.

**Closed** 2016-03-30 08:19 UTC
Labels: Duplicate

**Comment by ke7ofi** [comment] 2016-03-31 04:25
Maybe I should start using GH's saved reply feature for these.
