### ISSUE TITLE
Middle-clicking doesn't do anything.

### ISSUE THREAD

**Issue by ke7ofi** [QupZilla/qupzilla#1909] opened 2016-04-01 17:29 UTC
It used to open the link in a new tab, but on upgrading to version 2, it's stopped. This is on Void Linux, if that matters.

**Comment by nowrep** [comment] 2016-04-01 17:31
It works fine for me.
Do you have a specific webpage where it doesn't work?

**Comment by ke7ofi** [comment] 2016-04-01 17:50
Any of them! I first noticed it on https://uvesway.wordpress.com/2012/03/24/irssi-and-tmux-or-screen/, but it's a problem everywhere.

**Comment by cranes-bill** [comment] 2016-04-01 18:18
Works flawlessly to me.

**Comment by ke7ofi** [comment] 2016-04-01 20:30
That's strange. Maybe I'll have some more luck after restarting.

**Comment by ke7ofi** [comment] 2016-04-01 20:31
By the way, what's "spatial navigation"? Is there a setting that could have been changed when my profile was replaced?

**Comment by nowrep** [comment] 2016-04-02 09:35
Does right click (context menu) works fine on links/selected text/images ...?

**Comment by ke7ofi** [comment] 2016-04-03 22:01
It does.

**Comment by cranes-bill** [comment] 2016-04-05 10:12
You saying ..._upgrading to version 2_...
Did you checked with clean profile? My guess some of older settings make a mess.

**Comment by ke7ofi** [comment] 2016-04-05 14:50
That's possible, but when I fired it up after updating, it said that my olld settings had been exported, and everything was set to defaults (I thought, at least). Is it worth creating a new profile?

**Comment by cranes-bill** [comment] 2016-04-06 05:06
Just close all running QupZilla instances and run the following from the terminal par example: `HOME=/tmp/test qupzilla` , 
and see if it still doesn't works!

**Comment by nowrep** [comment] 2016-04-06 14:51
Maybe same as #1927 ? Do you have zoom other than 100%?

**Comment by ke7ofi** [comment] 2016-04-06 18:39
@cranes-bill same result

@nowrep Right-clicking works fine at all zoom levels, and I'm at 100%.

**Comment by cranes-bill** [comment] 2016-04-07 14:45
So, the problem is not caused from the settings...

**Comment by ke7ofi** [comment] 2016-04-07 16:35
This is going to be very difficult to replicate, then. Do any of you feel like flying out to the US to try it out on my computer?

**Comment by r-a-v-a-s** [comment] 2016-04-07 17:01
Does middle-click work for anything (e.g. closing/opening tabs, AutoScroll, etc...)?

**Comment by ke7ofi** [comment] 2016-04-07 17:24
I still don't understand AutoScroll, but it works fine on the tab bar.

**Comment by r-a-v-a-s** [comment] 2016-04-07 17:29
With the AutoScroll extension enabled, middle-click somewhere on a webpage and then move your mouse up and down to scroll. Up and down arrows will appear where you click.

**Comment by ke7ofi** [comment] 2016-04-07 17:35
Oh, I see. I'm on a ThinkPad, so that's similar to the standard scrolling method. I did check, and autoscroll works fine.

**Comment by r-a-v-a-s** [comment] 2016-04-07 17:58
Does ctrl + left-click work?

**Comment by ke7ofi** [comment] 2016-04-07 22:46
Yes, that's what I've been using until this is fixed.

**Comment by r-a-v-a-s** [comment] 2016-04-07 23:47
It's possibly a Chromium issue.
https://bugs.chromium.org/p/chromium/issues/detail?id=449467
https://bugs.chromium.org/p/chromium/issues/detail?id=156807

Interestingly some people noted updating ad-block or disabling it solved the issue for them.
Others noted that tweaking their mouse settings solved it.

**Comment by ke7ofi** [comment] 2016-04-08 02:05
Was QtWebEngine originally developed for Chromium?

**Comment by r-a-v-a-s** [comment] 2016-04-08 02:23
> QtWebEngine integrates chromium's fast moving web capabilities into Qt.
Our goal is to bring the latest and best implementation of the web platform into the universe of Qt. It is not just a port of the core HTML/CSS rendering engine, it is the entire Chromium platform.

http://wiki.qt.io/QtWebEngine

> ...we are seeing that Chromium is currently by far the most dynamic and fastest moving browser available. Basing our next-generation Web engine on Chromium is a strategic and long-term decision.

http://blog.qt.io/blog/2013/09/12/introducing-the-qt-webengine/

**Comment by ke7ofi** [comment] 2016-04-08 02:25
Is that a good thing?

**Comment by r-a-v-a-s** [comment] 2016-04-08 02:52
For me the performance of the old WebKit was unacceptable on certain websites.

Something else to note from the blog:

> Chromium has a cross-platform focus, with the browser being available on all major desktop platforms and Android. The same is no longer true of WebKit, and we would have had to support all the OS’es on our own in that project.

**Comment by cranes-bill** [comment] 2016-04-08 05:16
@ke7ofi 
Earlier i had an idea to make a live image, but @nowrep  said that [is just too much for one app](https://github.com/QupZilla/qupzilla/issues/1902#issuecomment-202916263)...
But you can test with live image so that will reject or confirm a problem related to your system, so i can make one for you if you want?

**Comment by Martii** [comment] 2016-04-08 05:24
@cranes-bill 
I think it's because of it's HUGE nature... most distro's live is about 1.2GB and that's a rather large file to download even if it was a .vdi for Virtual Box or whatever VMWare uses. Since I've never used an xdg-app I presume it's just a sandboxed application which could be much smaller but I have no idear what to run it in yet.

**Comment by ke7ofi** [comment] 2016-04-09 22:34
@cranes-bill What do you mean? Are you trying to make a QupzillaBook?

**Comment by cranes-bill** [comment] 2016-04-10 04:57
Just [**live disk**](https://en.wikipedia.org/wiki/Live_CD), but with latest prinstaled QupZilla snapshot included.
Regarding @Martii's comment, it will not be more then 800 Mb.

**Comment by ke7ofi** [comment] 2016-04-10 16:44
I didn't have any trouble with this on Arch (or Void, in previous versions). Do you want me to install X etc. on a Void live image to make sure there's nothing I've done interfering?

**Comment by Martii** [comment] 2016-04-10 17:20
If I may... please check your distro's package manager for `xev`... just to be sure that all events are being sent from your mouse. I burn through mice constantly *(as well as develop with it)* and that binary has been a godsend.

**Comment by cranes-bill** [comment] 2016-04-10 19:51
Well, you already tried on different system and since it works there, so that's not a QupZilla issue (IMHO).
Maybe you should report to distribution developers about this problem...

**Comment by ke7ofi** [comment] 2016-04-10 23:52
Maybe it's interfering with a package I have installed? How many of you are using libinput? I use xev to figure out my i3 bindings for function keys, so it's already installed. Running it, the entry for the middle mouse button is:

```
ButtonPress event, serial 33, synthetic NO, window 0x3800001,
    root 0xc4, subw 0x0, time 379054816, (331,423), root:(333,462),
    state 0x0, button 2, same_screen YES

ButtonRelease event, serial 33, synthetic NO, window 0x3800001,
    root 0xc4, subw 0x0, time 379054816, (331,423), root:(333,462),
    state 0x200, button 2, same_screen YES
```

**Comment by Martii** [comment] 2016-04-11 01:01
Here's mine:

``` sh-session
ButtonPress event, serial 40, synthetic NO, window 0x8c00001,
    root 0x294, subw 0x0, time 5005949, (31,176), root:(726,426),
    state 0x10, button 2, same_screen YES

ButtonRelease event, serial 40, synthetic NO, window 0x8c00001,
    root 0x294, subw 0x0, time 5006133, (31,176), root:(726,426),
    state 0x210, button 2, same_screen YES
```

> Maybe it's interfering with a package I have installed?

Probably not but if your evdev rules are misconfigured that can lead to kaos system wide... did your distro detect your mouse or did you hand configure it?

> How many of you are using libinput?

I am **not**. I think I saw that on ArchLinux as an option but I'm used to evdev and that's what the my main distro uses by default.

**Comment by ke7ofi** [comment] 2016-04-11 01:40
The other thing I can think of that might be interfering is that I've been using xinput to make my TrackPoint scrolling work properly. Here are the relevant lines from my xinitrc:

```
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1 &
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2 &
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200 &
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5 &
```

**Comment by JHooverman** [comment] 2016-04-16 09:45
Works with:

Application version: 2.0.0 (e5460538c8)
Qt version: 5.6.1
Platform: openSUSE Tumbleweed (Linux)

**Comment by Grarap** [comment] 2016-07-12 19:36
I'm having the same issue. It does however work when I click slightly longer than I normally would. That was not necessary in Qupzilla 1.x.

**Comment by Grarap** [comment] 2016-07-12 19:36
I'm having the same issue. It does however work when I click slightly longer than I normally would. That was not necessary in Qupzilla 1.x.

**Comment by AndydeCleyre** [comment] 2016-07-19 15:46
I too am experiencing this with a Thinkpad, on Arch, after the update. Middle-click does close tabs. I found that *double* middle-clicking a link will open it in a new tab.

I'm using Plasma Desktop, with this script in my user's autostart list:

```python
#!/usr/bin/env python3
from plumbum.cmd import xinput


trackpoint_done = touchpad_done = False
for device in xinput('list', '--id-only').split():
    properties = xinput('list-props', device)
    if not trackpoint_done and 'TrackPoint' in properties:
        for prop in (
            ('Evdev Wheel Emulation', '1'),
            ('Evdev Wheel Emulation Button', '2'),
            ('Evdev Wheel Emulation Axes', '6', '7', '4', '5'),
            ('Evdev Middle Button Emulation', '0')
        ):
            xinput('set-prop', device, prop)
        trackpoint_done = True
    elif not touchpad_done and 'TouchPad' in properties:
        xinput('set-prop', device, 'Device Enabled', '0')
        touchpad_done = True
    if trackpoint_done and touchpad_done:
        break
```

The purpose of that script is to disable the touchpad, and set up the trackpoint-plus-middle-button maneuver for scrolling.

**Comment by taranarmo** [comment] 2016-08-10 09:54
Hi, I have same issue on Manjaro Linux. QupZilla was updated in its repos recently with reset all settings. Double Middle click does open link in new created tab. I am also on thinkpad (x61). Middle click on a tab closes it.

**Comment by MikeWallaceDev** [comment] 2017-02-02 14:25
I am also having this problem. Middle click simply opens the link in the current tab. I was not able to double middle click as I don't seem to be fast enough :)  I am on Antergos. The link that I see here is that the problem seems to be happening on Arch related distros.
FYI : middle click does work in Midori

Application version 2.0.2
QtWebEngine version 5.7.0

**Comment by stefonarch** [comment] 2017-02-04 08:47
Same here for some days now, up-to-date arch
[2017-02-01 14:07] upgraded qt5-webengine (5.7.1-2 -> 5.8.0-1)

**Comment by nowrep** [comment] 2017-02-04 10:25
I have released 2.1.0, please test it (when it's in Arch) and report back.

**Comment by glesik** [comment] 2017-02-04 12:27
Works here with today's qupzilla-git 2.1.0 from AUR using QtWebEngine 5.7.1!

**Comment by stefonarch** [comment] 2017-02-04 13:26
Confirming that git version from AUR works.

> [2017-02-04 14:25] removed qupzilla (2.0.2-1)
> [2017-02-04 14:25] installed qupzilla-git (v2.1.0.r0.g4062473e-1)

**Comment by nowrep** [comment] 2017-02-05 10:21
Thanks, closing as fixed.

**Closed by nowrep** 2017-02-05 10:21 UTC
Labels: 2.0, Bug

**Comment by MikeWallaceDev** [comment] 2017-02-06 14:38
Also confirming that it's working.  Thanks!!
