### ISSUE TITLE
Qupzilla problems with internet connection

### ISSUE THREAD

**Issue by guillefar** [QupZilla/qupzilla#1928] opened 2016-04-07 01:11 UTC
I'm using a new laptop that occasionally has issues with the wifi connection. Usually, I restart network manager and the connection start to work fine, except for Qupzilla. It gave me the message "Network is disabled", even if every other program can connect just fine. 
Pressing the button to try again doesn't solve the issue, I have to restart it, and it works again. 
Any ideas?

**Comment by ke7ofi** [comment] 2016-04-07 02:31
This is a duplicate of #1744, #1750, #1845, and #1885.

**Comment by guillefar** [comment] 2016-04-07 08:09
Sorry, I did look for a similar problem, but seems that not good enough.

**Comment by ke7ofi** [comment] 2016-04-07 14:41
Don't worry about it. It's an upstream problem, so we'll just have to wait.

**Closed** 2016-04-08 09:33 UTC
Labels: Duplicate
