### ISSUE TITLE
no network access after suspend

### ISSUE THREAD

**Issue by lyro** [QupZilla/qupzilla#1845] opened 2016-01-26 12:19 UTC
When resuming my laptop after suspend, I cannot open any web site. Qupzilla answers with "Der Zugriff auf das Netzwerk ist nicht gestattet", which is German for "Access to network is not permitted". If I close Qupzilla and restart, the connection works again.

I know that this is not a very useful bug report (sorry for that), but currently I do not know how to get more information. What does this message mean? What can be the reason? What can I to to get more information (is there a log console or something)?

**Comment by nowrep** [comment] 2016-01-26 12:20
I'm sorry, but this is issue with Qt. What version do you use?

**Comment by lyro** [comment] 2016-01-26 12:31
I'm using Arch linux and qupzilla from the main repo, so I it should be
Qupzilla 1.8.9 with Qt 5.5.1

**Comment by ke7ofi** [comment] 2016-01-26 19:01
duplicate of #1744 and #1750, possibly others

**Comment by lyro** [comment] 2016-01-26 20:49
I see, sorry for the noise

**Closed** 2016-01-26 20:49 UTC
Labels: Qt
