### ISSUE TITLE
Option to force user-selected fonts for all websites

### ISSUE THREAD

**Issue by Nicky726** [QupZilla/qupzilla#1886] opened 2016-03-16 23:22 UTC
Suggestion: Add optional configuration which would enforce usage of user-selected fonts on all websites. Although user-selected fonts are configured in QupZilla (Linux Libertine/Biolinum in my case), preferences of websites are prefered.

**Comment by jamesqf** [comment] 2016-03-18 21:24
Can't you already do this with a user CSS?  Seems to work for me, as this bit copied from mine:

[code]* 
{
  color: white !important;
  background-color: black !important;
  background-image: black !important;
  font: 18px/1.4em normal normal Sassoon, Arial, Helvetica, sans-serif !important;
  text-align: left                    !important;
}
[/code]

**Comment by Vistaus** [comment] 2016-03-19 18:59
This is a duplicate of: https://github.com/QupZilla/qupzilla/issues/1240

**Closed** 2016-03-19 18:59 UTC
Labels: Duplicate
