### ISSUE TITLE
h264 html5

### ISSUE THREAD

**Issue by fcore117** [QupZilla/qupzilla#2009] opened 2016-06-21 12:46 UTC
Looks like Qupzilla really starts to reach stage where it can start push other browsers, one thing i would need is h264 html5 playback and i could quit Chromium usage in future. Perhaps FFMpeg based like Chromium has not like those others that use OS based plugins. FFMpeg based would be most optimal.

**Comment by nowrep** [comment] 2016-06-21 13:10
Duplicate of #1973

**Closed by nowrep** 2016-06-21 13:10 UTC
Labels: Duplicate
