### ISSUE TITLE
Download Manager fails with images

### ISSUE THREAD

**Issue by ruegerjr** [QupZilla/qupzilla#1606] opened 2015-02-16 23:25 UTC
Qupzilla 1.8.6 Download Manager hangs nearly every time when downloading small images (png,jpg) on my arch linux 64 bit system with an LXQT desktop.  The manager window shows 1 kb downloaded, 0 percent,  and progress bar animation, but no more progress.
-> Occurs only with image files smaller than 1-2 MB in size.
-> This occurs regardless of any other settings in download preferences (I've tried changing all except  for external download manager).
-> Occurs for any user, including ROOT
-> Does NOT occur for other (non-image?) file types (links) downloaded.
-> No error messages to console - not a complete crash

**Comment by JHooverman** [comment] 2015-02-17 18:07
Please follow this step-by-step procedure:


* Go to this page:
http://www.amazon.de/Number-Ones-Jackson-Michael/dp/B0000E4N57/ref=sr_1_3?s=music&ie=UTF8&qid=1424195737&sr=1-3&keywords=michael+jackson

* Click on the CD cover

* A new window appears

* Do a right click on the image

* Select `Save image as...`

* Select a location where to save the image

* Hit `Save`

* The Download Manager appears

* The download does not continue

![down](http://i.imgur.com/WfFvbbh.png)

* However, cancelling the download and answering `No` in this dialog will save the image.

![down2](http://i.imgur.com/JpLDeey.png)

QtTestBrowser works as expected.


Tested with:

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Feb 8 2015 10:30:39
Platform: openSuSE Tumbleweed (Linux)

**Comment by ruegerjr** [comment] 2015-02-18 01:28
This workaround indeed works for me.  Thank you

**Comment by JHooverman** [comment] 2015-02-18 12:21
@nowrep: Are you able to reproduce this issue?

**Comment by pejakm** [comment] 2015-02-18 13:52
I experience this randomly, too.

**Comment by cranes-bill** [comment] 2015-02-18 17:59
I can reproduce it with Qt 5 only, never occurs with Qt 4.

**Comment by MttCastelli** [comment] 2015-03-18 13:08
@JHooverman issue reproduced here, and also the workaround works. The issue stands trough.

LXQt Desktop Toolbox - Technical Info<p>
  Version:                0.9.0
  Qt:                     5.4.0
  Build type:             Release
 
Versione dell'applicazione 1.8.6 (n/a)
Versione di WebKit 538.1

Platform: Ubuntu 15.04 vivid (dev. branch) + lubuntu-dev daily PPA

**Comment by JHooverman** [comment] 2015-04-12 12:32
In addition, the download dialog sometimes shows weird information:

![dl1](http://i.imgur.com/cXQR8UU.png)

**Comment by OlafLostViking** [comment] 2015-06-11 19:27
Just adding my "me too" with QupZilla 1.8.6 and Qt5 on ArchLinux (KDE 4).

**Comment by tachyonimpact** [comment] 2015-06-12 20:59
This is still an issue. All image downloads appear in the download manager to halt at 1kb.

**Comment by willbprog127** [comment] 2015-09-06 18:08
Exact same issue here, latest git as of the build date shown below.

-- 

:information_source: 
Application version: `1.8.6`
Qt version: `5.4.1`
WebKit version: `538.1`
Build time: `Sep 1 2015 11:19:58`
Platform: `BSD 4.4  (FreeBSD 10.2)`

**Comment by nowrep** [comment] 2015-09-06 18:18
@willbprog127 Can you please post some image that triggers this problem? I still can't seem to reproduce it ...

**Comment by willbprog127** [comment] 2015-09-06 18:22
- Open http://www.pismotek.com/media/newstart.png in QupZilla
- Right-click the picture and choose 'Save image as...'
- File save dialog will pop up.  Choose directory then click 'Save'
- Download manager will start download (and the file *does* save) but never finishes download according to the download manager.

**Comment by JHooverman** [comment] 2015-09-06 18:24
@nowrep: Please follow the instructions in my post on 17.02.2015 (it is the second post in this issue). However, I did not try this with the latest git version.

**Comment by nowrep** [comment] 2015-09-06 18:26
I did, works for me :D (Qt 5.4:2) .. Trying now with Qt 5.5

**Comment by willbprog127** [comment] 2015-09-06 18:28
Trying to do a screen capture so you can see...

**Comment by nowrep** [comment] 2015-09-06 18:29
No need, I know what is the problem, I just can't reproduce it :)

**Comment by nowrep** [comment] 2015-09-06 18:30
Can you please build with this line uncommented: https://github.com/QupZilla/qupzilla/blob/v1.8/src/lib/downloads/downloaditem.cpp#L42
And show me the terminal output?

**Comment by willbprog127** [comment] 2015-09-06 18:34
@nowrep Do you mean the build output or running after build?

**Comment by nowrep** [comment] 2015-09-06 18:35
Run after build - try to download some image and trigger this bug.

**Comment by JHooverman** [comment] 2015-09-06 18:36
@willbprog127: Will you be able to do what nowrep suggested? I am currently on vacation and will not return before Sep, 13.

**Comment by willbprog127** [comment] 2015-09-06 18:51
Here's the output

```
NetworkManager::addLocalCertificate cannot write to file:  "/usr/home/will/(1).config/qupzilla/profiles/default/certificates/crt"
/usr/local/lib/nspluginwrapper/i386/linux/npviewer: not found
DownloadItem 0x8150bc880 QNetworkReplyHttpImpl(0x8150a2a10) "/usr/home/will/Downloads/" "newstart.png"
readyRead
updateDownload
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
updateDownloadInfo 8.9007e-308 0 4386
stop
error 5
downloadProgress 0 4386
finished QNetworkReplyHttpImpl(0x8150a2a10)
```

**Comment by nowrep** [comment] 2015-09-08 09:29
Can you try it without native dialogs? (Preferences -> Downloads -> uncheck "Use native dialogs")

**Comment by willbprog127** [comment] 2015-09-08 15:43
Hi.  I already am using QupZilla without native dialogs.

**Comment by nowrep** [comment] 2015-09-08 16:02
Ok, and does it make any difference if you try with/without native dialogs?

**Comment by willbprog127** [comment] 2015-09-08 16:15
When I try with native dialogs, it still uses the Qt dialog.  I tried anyway and it still is having the problem.

**Comment by willbprog127** [comment] 2015-09-08 17:05
I'm not sure if QupZilla is looking for an environment variable to determine what type of 'native' dialog it should use, but my desktop environment is Openbox and fbpanel.  I am not using Gnome, KDE, etc.

**Comment by nowrep** [comment] 2015-10-02 15:40
Yeah, all file dialogs are now native with Qt 5 (when you have integration plugin of your DE).

Anyway, I still can't reproduce the issue ..

**Comment by willbprog127** [comment] 2015-10-02 15:55
@nowrep Okay, thanks for trying.  I'm currently off of FreeBSD and QupZilla so no way to test anymore.

**Comment by cranes-bill** [comment] 2015-11-12 15:58
I'm just posting the following:
```
DownloadItem 0x767a3c0 QNetworkReplyHttpImpl(0x75caee0) "/home/az/Bureau/" "710rHfRMhGL._SL1500_.jpg" (../../../src/lib/downloads/downloaditem.cpp:62, DownloadItem::DownloadItem(QListWidgetItem*, QNetworkReply*, const QString&, const QString&, const QPixmap&, QTime*, bool, const QUrl&, DownloadManager*))
readyRead (../../../src/lib/downloads/downloaditem.cpp:440, void DownloadItem::readyRead())
updateDownload (../../../src/lib/downloads/downloaditem.cpp:467, void DownloadItem::updateDownload())
updateDownloadInfo 6.90099e-310 0 87190 (../../../src/lib/downloads/downloaditem.cpp:290, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 6.90099e-310 0 87190 (../../../src/lib/downloads/downloaditem.cpp:290, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 6.90099e-310 0 87190 (../../../src/lib/downloads/downloaditem.cpp:290, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
stop (../../../src/lib/downloads/downloaditem.cpp:319, void DownloadItem::stop(bool))
error 5 (../../../src/lib/downloads/downloaditem.cpp:453, void DownloadItem::error())
downloadProgress 0 87190 (../../../src/lib/downloads/downloaditem.cpp:216, void DownloadItem::downloadProgress(qint64, qint64))
finished QNetworkReplyHttpImpl(0x75caee0) (../../../src/lib/downloads/downloaditem.cpp:181, void DownloadItem::finished())
```

**Comment by cranes-bill** [comment] 2015-11-13 06:55
I don't know if this fix is related to my previous comment here, but just to say that i'm still receiving the same messages from debugger.

**Comment by nowrep** [comment] 2015-11-13 11:18
@cranes-bill It should only fix `updateDownloadInfo 6.90099e-310 0 87190` -> `updateDownloadInfo 0 0 87190`

**Comment by nowrep** [comment] 2015-11-13 11:23
@cranes-bill Can you please post output with this:

```diff
diff --git a/src/lib/downloads/downloaditem.cpp b/src/lib/downloads/downloaditem.cpp
index 061260d..69d8e4e 100644
--- a/src/lib/downloads/downloaditem.cpp
+++ b/src/lib/downloads/downloaditem.cpp
@@ -465,7 +465,7 @@ void DownloadItem::error()
 void DownloadItem::updateDownload()
 {
 #ifdef DOWNMANAGER_DEBUG
-    qDebug() << __FUNCTION__ ;
+    qDebug() << __FUNCTION__ << "reply finished" << m_reply->isFinished();
 #endif
     // after caling stop() (from readyRead()) m_reply will be a dangling pointer,
     // thus it should be checked after m_outputFile.isOpen()
```

**Comment by cranes-bill** [comment] 2015-11-13 11:52
Sure, but it looks the same:
```
DownloadItem 0x5dd5440 QNetworkReplyHttpImpl(0x5be3f10) "/home/az/Bureau/" "710rHfRMhGL._SL1500_.jpg" (../../../src/lib/downloads/downloaditem.cpp:63, DownloadItem::DownloadItem(QListWidgetItem*, QNetworkReply*, const QString&, const QString&, const QPixmap&, QTime*, bool, const QUrl&, DownloadManager*))
readyRead (../../../src/lib/downloads/downloaditem.cpp:441, void DownloadItem::readyRead())
updateDownload reply finished false (../../../src/lib/downloads/downloaditem.cpp:468, void DownloadItem::updateDownload())
updateDownloadInfo 0 0 87190 (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 0 0 87190 (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 0 0 87190 (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 0 0 87190 (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
stop (../../../src/lib/downloads/downloaditem.cpp:320, void DownloadItem::stop(bool))
error 5 (../../../src/lib/downloads/downloaditem.cpp:454, void DownloadItem::error())
downloadProgress 0 87190 (../../../src/lib/downloads/downloaditem.cpp:217, void DownloadItem::downloadProgress(qint64, qint64))
finished QNetworkReplyHttpImpl(0x5be3f10) (../../../src/lib/downloads/downloaditem.cpp:182, void DownloadItem::finished())
```

**Comment by nowrep** [comment] 2015-11-13 11:57
Ok, another try:

```diff
diff --git a/src/lib/downloads/downloaditem.cpp b/src/lib/downloads/downloaditem.cpp
index 061260d..3734f79 100644
--- a/src/lib/downloads/downloaditem.cpp
+++ b/src/lib/downloads/downloaditem.cpp
@@ -288,7 +288,7 @@ QString DownloadItem::currentSpeedToString(double speed)
 void DownloadItem::updateDownloadInfo(double currSpeed, qint64 received, qint64 total)
 {
 #ifdef DOWNMANAGER_DEBUG
-    qDebug() << __FUNCTION__ << currSpeed << received << total;
+    qDebug() << __FUNCTION__ << currSpeed << received << total << m_reply->isFinished();
 #endif
     //            QString          QString       QString     QString
     //          | m_remTime |   |m_currSize|  |m_fileSize|  |m_speed|

```

**Comment by cranes-bill** [comment] 2015-11-13 12:17
The same again, i think:
```
DownloadItem 0x591f020 QNetworkReplyHttpImpl(0x4600ea0) "/home/az/Bureau/" "710rHfRMhGL._SL1500_.jpg" (../../../src/lib/downloads/downloaditem.cpp:63, DownloadItem::DownloadItem(QListWidgetItem*, QNetworkReply*, const QString&, const QString&, const QPixmap&, QTime*, bool, const QUrl&, DownloadManager*))
readyRead (../../../src/lib/downloads/downloaditem.cpp:441, void DownloadItem::readyRead())
updateDownload (../../../src/lib/downloads/downloaditem.cpp:468, void DownloadItem::updateDownload())
updateDownloadInfo 0 0 87190 false (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 0 0 87190 false (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 0 0 87190 false (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
updateDownloadInfo 0 0 87190 false (../../../src/lib/downloads/downloaditem.cpp:291, void DownloadItem::updateDownloadInfo(double, qint64, qint64))
stop (../../../src/lib/downloads/downloaditem.cpp:320, void DownloadItem::stop(bool))
error 5 (../../../src/lib/downloads/downloaditem.cpp:454, void DownloadItem::error())
downloadProgress 0 87190 (../../../src/lib/downloads/downloaditem.cpp:217, void DownloadItem::downloadProgress(qint64, qint64))
finished QNetworkReplyHttpImpl(0x4600ea0) (../../../src/lib/downloads/downloaditem.cpp:182, void DownloadItem::finished())
```
**BTW**: The compiller has reported some warning about debug function, but i missed it. If it's important, i will recompile with redirecting output...

**Comment by nowrep** [comment] 2015-11-13 12:19
Well, now it looks that it is actually Qt issue because the `QNetworkReply::isFinished() == false` but it actually already finished (as you can stop the download and everything is saved correctly).

No, debug compiler warnings doesn't matter.

**Comment by cranes-bill** [comment] 2015-11-13 16:09
I found that if i open an image in QupZilla and leave it for few minutes, then the problem disappears.
As well as i open a local image file via menu, i can use download function without problem.
I hope the above is a good clue....

**Comment by innermous** [comment] 2015-12-12 22:01
Have this aswell under archlinux, qupzilla  v1.8.9

**Comment by seisatsu** [comment] 2015-12-13 18:56
I am also seeing this issue still under Void Linux with QupZilla v1.8.9.

**Comment by nowrep** [comment] 2016-12-26 19:26
This should be fixed in QupZilla 2.

**Closed by nowrep** 2016-12-26 19:26 UTC
Labels: Bug
