### ISSUE TITLE
Can't read Youtube Video

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [QupZilla/qupzilla#1663] opened 2015-05-30 10:51 UTC
Qupzilla can't read Youtube Video
The lenght displayed is of 0:00/

I don't use Flash, but HTML5 reader is activated.

**Comment by JHooverman** [comment] 2015-05-30 11:17
HTML5-videos generally work in QupZilla:

![html5](http://i.imgur.com/5VRWkus.png)

Please check:
- Your AdBlock settings, maybe try to disable it completely
- Go to [this](http://html5test.com/) link and verify the capabilities of your QtWebkit-components

For me it looks like this:

![im2](http://i.imgur.com/zLzM9vz.png)

**Comment by schyzophrene-asynchrone** [comment] 2015-05-30 11:22
Adblock disabled.
I have the same results as you at the html5 test.
Still doesn't work...

**Comment by JHooverman** [comment] 2015-05-30 11:41
Would you please try the HTML5-tests on [this](http://www.quirksmode.org/html5/tests/video.html) page?

**Comment by schyzophrene-asynchrone** [comment] 2015-05-30 11:47
I can't read any of the video under the table...

**Comment by JHooverman** [comment] 2015-05-30 11:54
Would you please verify, that `Allow Netscape Plugins` is unchecked

![im3](http://i.imgur.com/t80JElb.png)

**Comment by schyzophrene-asynchrone** [comment] 2015-05-30 12:04
> Would you please verify, that `Allow Netscape Plugins` is unchecked
It is unchecked.

**Comment by JHooverman** [comment] 2015-05-30 12:32
To determine, if the problem is caused by QupZilla or the Qt-framework, you are kindly asked to do the same tests with another Qt5-browser.

You might try
- [Otter-Browser](http://otter-browser.org/)
- [QtTestBrowser](http://cloud.qupzilla.com/public.php?service=files&t=15d78bb1cf2b813aa5a496c0a8b063a7)

However, the latter one you will have to compile by yourself.

**Comment by cranes-bill** [comment] 2015-05-30 13:29
Installing of `gstreamer1.0-libav` should solved your problem.

**Comment by JHooverman** [comment] 2015-05-30 13:38
@schyzophrene-asynchrone: You might want to look at [this](https://github.com/QupZilla/qupzilla/issues/1571) issue as well. It will show you, which gstreamer-packages will have to be installed.

@cranes-bill: Thank you for reminding me.

**Comment by cranes-bill** [comment] 2015-06-01 07:10
@JHooverman You are always welcome :wink:
By the way, can you play [this](http://www.atpworldtour.com/Media/Video-Landing.aspx) video for example? It stuck to loading screen to me with Qupzilla, but works with Firefox.

**Comment by schyzophrene-asynchrone** [comment] 2015-06-01 13:51
I'm compiling QtTestBrowser.
Installing the gstreamer packages doesn't change anything (but I have gstreamer1.0 and the topic is about gstreamer0.10)

I tell you if can read videos with QtTestBrowser.

**Comment by schyzophrene-asynchrone** [comment] 2015-06-01 13:58
QtTestBrowser can't read anything neither...
I'm using Qt5.3.

**Comment by cranes-bill** [comment] 2015-06-01 14:35
These packages are available for Debian:
```
gstreamer0.10-alsa
gstreamer0.10-chromaprint
gstreamer0.10-dvswitch
gstreamer0.10-fluendo-mp3
gstreamer0.10-gconf
gstreamer0.10-gnomevfs
gstreamer0.10-gnonlin
gstreamer0.10-hplugins
gstreamer0.10-nice
gstreamer0.10-plugins-bad
gstreamer0.10-plugins-base
gstreamer0.10-plugins-base-apps
gstreamer0.10-plugins-good
gstreamer0.10-plugins-ugly
gstreamer0.10-pocketsphinx
gstreamer0.10-pulseaudio
gstreamer0.10-qapt
gstreamer0.10-tools
gstreamer0.10-x
gstreamer1.0-alsa
gstreamer1.0-clutter
gstreamer1.0-crystalhd
gstreamer1.0-fluendo-mp3
gstreamer1.0-gnonlin
gstreamer1.0-libav
gstreamer1.0-nice
gstreamer1.0-packagekit
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base
gstreamer1.0-plugins-base-apps
gstreamer1.0-plugins-good
gstreamer1.0-plugins-ugly
gstreamer1.0-pulseaudio
gstreamer1.0-tools
gstreamer1.0-vaapi
gstreamer1.0-x
gstreamer-tools
```
From **Multimedia Main** repository:
```
gstreamer0.10-ffmpeg
gstreamer0.10-plugins-really-bad
gstreamer1.0-libav
```
The packages with **plugins** in the name are very important, as **libav** and **ffmpeg** as well.
Check what you are missing!

**Comment by schyzophrene-asynchrone** [comment] 2015-06-01 18:02
I installed all these packages.
I can now read the sound of Youtube video and WebM video here : http://www.quirksmode.org/html5/tests/video.html
I still can't read MP4 or OGG/Theora...

**Comment by cranes-bill** [comment] 2015-06-01 19:00
There is 2 **gstreamer1.0-libav** packages in the lists above. Try to replace that you have installed with other one. My guess the „*Multimedia*“ package is better.
Sorry for my bad English!

**Comment by schyzophrene-asynchrone** [comment] 2015-06-02 10:12
I already have the package from the deb-multimedia repository.
apt always choose the latest version available (unless i tell not to, but I don't know how)

**Comment by cranes-bill** [comment] 2015-06-02 13:20
I've used Debian many years ago, so can't remember the APT features.You might use DPKG instead.
Even i'm no longer sure this will solve your problem, although i had the same issue until installing this package. But i'm not on Debian and my version of the package is a quite old - **1.0.6**.
In any case the problem is in your system, not in Qupzilla, so perhaps you might try to find a solution in any Debian forum, unless any guy here have a better propose.

**Comment by JHooverman** [comment] 2015-06-04 10:51
@cranes-bill: Regarding the video-link you sent me for testing: Did you activate the flash-cookie-manager plugin in QupZilla?

**Comment by cranes-bill** [comment] 2015-06-04 11:47
Yes, it allays active :white_check_mark: :smiley:
But now when you ask me, i've tried with clean profile, but have the same behavior.

**Comment by JHooverman** [comment] 2015-06-04 11:54
I am using the FCM as well and had the same problem as you described. After adding your testpage to the whitelist I got this result:

![im1](http://i.imgur.com/ruXelKr.png)

**Comment by JHooverman** [comment] 2015-06-04 11:59
@cranes-bill: I have to correct myself, I had to add it to this whitelist:

![im2](http://i.imgur.com/zzVjDUp.png)

**Comment by cranes-bill** [comment] 2015-06-04 12:25
But now it starts with *Flash player plugin* (my guess).

**Comment by JHooverman** [comment] 2015-06-04 12:52
Yes, this is correct...

**Comment by cranes-bill** [comment] 2015-06-04 13:47
I.e. this video can't be played in HTML5 mode in Qupzilla...
OK, thank you for your time!

**Comment by JHooverman** [comment] 2015-06-04 13:58
Who do you force QupZilla to play this video in HTML5 mode?

**Comment by cranes-bill** [comment] 2015-06-04 14:21
Just removed the Flash player. But even it's not removed, the HTML5 videos automatically starts when it's possible.

**Comment by nowrep** [comment] 2015-10-02 15:32
This will be finally fixed with QtWebEngine.

**Closed by nowrep** 2015-10-02 15:32 UTC
Labels: Other
